"""Draft sanitizer + validator — enforces Julian's "human-typed, never AI" voice rules.

Every draft generated by opener.py / reply.py / date_ask.py must pass through
sanitize_draft(text) then validate_draft(text, persona) before being queued.

Rules (from clapcheeks_user_settings.persona.message_formatting_rules):
- ASCII-only punctuation. Banned: em-dash (U+2014), en-dash (U+2013),
  semicolon, ellipsis (U+2026), curly quotes, non-breaking space
- No "AI tells": long run-on sentences, em-dash-joined clauses, corny closers
- Banned_words list from persona.banned_words gets rejected
- Hard length caps from persona.message_formatting_rules.length.hard_max_chars
- Corny closers ("looking forward to hearing from you", ":)") rejected

PHASE-E — AI-8319
"""
from __future__ import annotations

import logging
import re
from typing import Any

logger = logging.getLogger(__name__)

# ---------------------------------------------------------------------------
# Banned punctuation — the "AI tell" set
# ---------------------------------------------------------------------------

# Chars that MUST never appear in a draft.
BANNED_CHARS: dict[str, str] = {
    "\u2014": "-",      # em-dash
    "\u2013": "-",      # en-dash
    "\u2026": "...",    # ellipsis
    "\u201c": '"',      # left curly double quote
    "\u201d": '"',      # right curly double quote
    "\u2018": "'",      # left curly single quote
    "\u2019": "'",      # right curly single quote
    "\u00a0": " ",      # non-breaking space
    "\u2022": "*",      # bullet
    "\u00b7": "*",      # middle dot
    "\u2192": "->",     # rightward arrow
}

# Chars that CAN be sanitized away, but if they remain after sanitizing we reject.
# Semicolons are a hard reject — there is no ASCII fallback we want.
HARD_REJECT_CHARS = {";"}

# Common "AI tell" closers — reject drafts containing these as stand-alone phrases.
CORNY_CLOSERS = [
    "looking forward to hearing from you",
    "looking forward to hearing back",
    "hope to hear from you soon",
    "let me know your thoughts",
    "have a great day",
    "have a wonderful day",
    "feel free to reach out",
    "don't hesitate to",
    "please don't hesitate",
    "cheers!",
    "best regards",
    "kind regards",
]

# Smiley "AI tell" — ":)" alone at end of message reads as fake warm.
CORNY_EMOTICONS = [":)", ":-)", ":D", ":-D"]

# Default fallback formatting rules when persona doesn't specify.
DEFAULT_RULES: dict[str, Any] = {
    "length": {
        "ideal_max_chars": 80,
        "hard_max_chars": 160,
    },
    "banned_punctuation": list(BANNED_CHARS.keys()) + list(HARD_REJECT_CHARS),
    "allowed_punctuation": [".", ",", "?", "!", "'", '"', "-", "(", ")", "/", ":"],
    "emoji_policy": {"max_emojis": 1, "early_convo_emojis": 0},
}


# ---------------------------------------------------------------------------
# Sanitizer — non-destructive replacements
# ---------------------------------------------------------------------------

def sanitize_draft(text: str) -> str:
    """Apply non-destructive replacements. Unicode punctuation -> ASCII equivalents.

    Does NOT remove banned_words (that's validate_draft's job — we want to
    reject those outright, not silently scrub them). Does NOT shorten length.
    """
    if not text:
        return text

    out = text
    for bad, good in BANNED_CHARS.items():
        out = out.replace(bad, good)

    # Collapse stray double-dashes that resulted from em-dash -> "-"
    out = re.sub(r"-{3,}", "-", out)

    # Trim leading/trailing whitespace
    return out.strip()


# ---------------------------------------------------------------------------
# Validator — boolean + error-list result
# ---------------------------------------------------------------------------

def _has_char(text: str, chars: set[str] | list[str]) -> list[str]:
    hits = []
    for c in chars:
        if c in text:
            hits.append(c)
    return hits


def _contains_phrase(text: str, phrases: list[str]) -> list[str]:
    low = text.lower()
    return [p for p in phrases if p.lower() in low]


def _count_emojis(text: str) -> int:
    # Rough emoji detection — any char in common emoji unicode blocks.
    # Good enough for post-sanitize text.
    count = 0
    for ch in text:
        o = ord(ch)
        if (
            0x1F300 <= o <= 0x1FAFF
            or 0x2600 <= o <= 0x27BF
            or 0x1F000 <= o <= 0x1F02F
            or 0x1F0A0 <= o <= 0x1F0FF
        ):
            count += 1
    return count


def validate_draft(
    text: str,
    persona: dict[str, Any] | None = None,
    conversation_stage: str = "mid",
) -> tuple[bool, list[str]]:
    """Return (ok, errors). ok=True means the draft is safe to queue.

    Rejects:
    - Any remaining banned Unicode punctuation (sanitize should've stripped this)
    - Semicolons (no automatic fix — they're an AI tell)
    - Any banned_word from persona.banned_words
    - Length above persona.message_formatting_rules.length.hard_max_chars
    - Corny closers / corny emoticons
    - Early convo emoji usage when persona enforces it

    conversation_stage: "early" (1st-2nd message) triggers stricter emoji rules.
    """
    errors: list[str] = []
    persona = persona or {}

    if not text or not text.strip():
        errors.append("empty draft")
        return False, errors

    # 1. Banned Unicode punctuation — if these remain, sanitize didn't run
    banned_hits = _has_char(text, BANNED_CHARS.keys())
    if banned_hits:
        errors.append(f"banned unicode punctuation: {banned_hits!r}")

    # 2. Hard-reject chars (semicolon)
    hard_hits = _has_char(text, HARD_REJECT_CHARS)
    if hard_hits:
        errors.append(f"banned punctuation: {hard_hits!r}")

    # 3. Banned words from persona
    banned_words: list[str] = persona.get("banned_words", []) or []
    low = text.lower()
    word_hits = [w for w in banned_words if w.lower() in low]
    if word_hits:
        errors.append(f"banned_words present: {word_hits!r}")

    # 4. Length cap
    rules = persona.get("message_formatting_rules", {}) or {}
    length = rules.get("length", {}) or {}
    hard_max = length.get("hard_max_chars", DEFAULT_RULES["length"]["hard_max_chars"])
    if len(text) > hard_max:
        errors.append(f"over hard_max_chars ({len(text)} > {hard_max})")

    # 5. Corny closers
    closer_hits = _contains_phrase(text, CORNY_CLOSERS)
    if closer_hits:
        errors.append(f"corny closer: {closer_hits!r}")

    # 6. Corny standalone emoticons
    stripped = text.strip()
    for emo in CORNY_EMOTICONS:
        if stripped.endswith(emo):
            errors.append(f"corny emoticon at end: {emo!r}")
            break

    # 7. Emoji policy
    emoji_policy = rules.get("emoji_policy", {}) or {}
    max_emojis = emoji_policy.get("max_emojis", DEFAULT_RULES["emoji_policy"]["max_emojis"])
    early_max = emoji_policy.get(
        "early_convo_emojis", DEFAULT_RULES["emoji_policy"]["early_convo_emojis"]
    )
    emoji_count = _count_emojis(text)
    if conversation_stage == "early" and emoji_count > early_max:
        errors.append(
            f"too many emojis for early convo ({emoji_count} > {early_max})"
        )
    elif emoji_count > max_emojis:
        errors.append(f"too many emojis ({emoji_count} > {max_emojis})")

    return (len(errors) == 0), errors


# ---------------------------------------------------------------------------
# Convenience — sanitize + validate in one shot
# ---------------------------------------------------------------------------

def sanitize_and_validate(
    text: str,
    persona: dict[str, Any] | None = None,
    conversation_stage: str = "mid",
) -> tuple[bool, str, list[str]]:
    """Run sanitize then validate. Returns (ok, cleaned_text, errors)."""
    cleaned = sanitize_draft(text)
    ok, errors = validate_draft(cleaned, persona, conversation_stage)
    return ok, cleaned, errors
