#!/bin/bash
set -e
echo "=== Clapcheeks Deployment ==="
echo ""
echo "1. Web (Vercel):"
echo "   cd web && vercel --prod"
echo ""
echo "2. API (Railway):"
echo "   cd api && railway up"
echo ""
echo "3. AI Service (Fly.io):"
echo "   cd ai && fly deploy"
echo ""
echo "Environment variables needed:"
echo "  Web:  copy web/.env.example → web/.env.local"
echo "  API:  copy api/.env.example → api/.env"
echo "  AI:   copy ai/.env.example  → ai/.env"
echo ""
echo "Domain config:"
echo "  clapcheeks.tech        → Vercel (DNS CNAME to cname.vercel-dns.com)"
echo "  api.clapcheeks.tech    → Railway (custom domain in Railway dashboard)"
echo "  ai.clapcheeks.tech     → Fly.io (fly certs add ai.clapcheeks.tech)"
