#!/bin/bash
set -e
echo "=== Clapcheeks Deployment ==="
echo ""
echo "STEP 1: Supabase migrations"
echo "   supabase db push"
echo "   (runs all 10 migrations in order)"
echo ""
echo "STEP 2: Stripe products"
echo "   Create products + prices with these lookup keys:"
echo "   starter_monthly  →  \$29/mo"
echo "   starter_annual   →  \$23/mo (\$276/yr)"
echo "   pro_monthly      →  \$59/mo"
echo "   pro_annual       →  \$47/mo (\$564/yr)"
echo "   elite_monthly    →  \$99/mo"
echo "   elite_annual     →  \$79/mo (\$948/yr)"
echo ""
echo "STEP 3: Set environment variables"
echo "   Web:  copy web/.env.example  → web/.env.local (fill in all values)"
echo "   API:  copy api/.env.example  → api/.env      (fill in all values)"
echo "   AI:   copy ai/.env.example   → ai/.env       (KIMI_API_KEY required)"
echo ""
echo "STEP 4: Deploy services"
echo "   cd web && vercel --prod"
echo "   cd api && railway up"
echo "   cd ai  && fly deploy"
echo ""
echo "STEP 5: Configure Supabase auth webhook"
echo "   In Supabase dashboard → Database → Webhooks:"
echo "   Table: auth.users | Event: INSERT"
echo "   URL: https://api.clapcheeks.tech/email/welcome"
echo ""
echo "STEP 6: DNS"
echo "   clapcheeks.tech        → Vercel  (CNAME to cname.vercel-dns.com)"
echo "   api.clapcheeks.tech    → Railway (custom domain in Railway dashboard)"
echo "   ai.clapcheeks.tech     → Fly.io  (fly certs add ai.clapcheeks.tech)"
echo ""
echo "Done — clapcheeks.tech is live."
