import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const files = {
  compat: readFileSync('lib/convex/compat-client.ts', 'utf8'),
  scheduledRoute: readFileSync('app/api/scheduled-messages/route.ts', 'utf8'),
  scheduledItemRoute: readFileSync('app/api/scheduled-messages/[id]/route.ts', 'utf8'),
  scheduledSendRoute: readFileSync('app/api/scheduled-messages/send/route.ts', 'utf8'),
  scheduledPage: readFileSync('app/(main)/scheduled/page.tsx', 'utf8'),
  intelligencePage: readFileSync('app/(main)/intelligence/page.tsx', 'utf8'),
  dashboardPage: readFileSync('app/(main)/dashboard/page.tsx', 'utf8'),
  briefingCard: readFileSync('app/(main)/dashboard/components/briefing-card.tsx', 'utf8'),
  appSidebar: readFileSync('components/layout/app-sidebar.tsx', 'utf8'),
  rosterCard: readFileSync('components/roster/RosterCard.tsx', 'utf8'),
  dailyTopThree: readFileSync('components/roster/DailyTopThree.tsx', 'utf8'),
  communicationsPage: readFileSync('app/(main)/communications/page.tsx', 'utf8'),
  communicationsConsole: readFileSync('app/(main)/communications/communications-console.tsx', 'utf8'),
  imessageTestRoute: readFileSync('app/api/imessage/test/route.ts', 'utf8'),
  imessageTestPanel: readFileSync('app/(main)/dashboard/components/imessage-test-panel.tsx', 'utf8'),
  packageJson: readFileSync('package.json', 'utf8'),
  browserVisualScript: readFileSync('scripts/e2e-browser-visual-safe.sh', 'utf8'),
  browserVisualCctScript: readFileSync('scripts/e2e-browser-visual-cct.mjs', 'utf8'),
  productionCctScript: readFileSync('scripts/e2e-production-cct.mjs', 'utf8'),
  completionAuditScript: readFileSync('scripts/e2e-completion-audit.mjs', 'utf8'),
  liveSendEvidenceScript: readFileSync('scripts/e2e-live-send-evidence.mjs', 'utf8'),
  liveSendApprovalPacketScript: readFileSync('scripts/e2e-live-send-approval-packet.mjs', 'utf8'),
  liveSendSamplePreflightScript: readFileSync('scripts/e2e-live-send-sample-preflight.mjs', 'utf8'),
  liveSendRehearsalScript: readFileSync('scripts/e2e-live-send-rehearsal.mjs', 'utf8'),
  liveSendEvidenceRefusalTest: readFileSync('__tests__/live-send-evidence-refusal.test.mjs', 'utf8'),
  readinessAllScript: readFileSync('scripts/e2e-readiness-all-safe.sh', 'utf8'),
  readinessLocalScript: readFileSync('scripts/e2e-readiness-local-safe.sh', 'utf8'),
  localBrowserProofScript: readFileSync('scripts/e2e-local-browser-proof.mjs', 'utf8'),
  backendDoctorScript: readFileSync('scripts/e2e-backend-doctor-safe.mjs', 'utf8'),
  runtimeSmokeScript: readFileSync('scripts/e2e-runtime-smoke-safe.mjs', 'utf8'),
  safeReadinessScript: readFileSync('scripts/e2e-readiness-safe.mjs', 'utf8'),
  liveSendRunbook: readFileSync('docs/e2e-live-send-runbook.md', 'utf8'),
  readinessStatusScript: readFileSync('scripts/e2e-readiness-status.mjs', 'utf8'),
  evidenceIndexScript: readFileSync('scripts/e2e-evidence-index.mjs', 'utf8'),
  liveSendPreflightScript: readFileSync('scripts/e2e-live-send-preflight.mjs', 'utf8'),
  liveSendPreflightExecTest: readFileSync('__tests__/live-send-preflight-exec.test.mjs', 'utf8'),
  tokenHealthRoute: readFileSync('app/api/agent/token-health/route.ts', 'utf8'),
  tokenHealthLib: readFileSync('lib/clapcheeks/token-health.ts', 'utf8'),
  replyGenerator: readFileSync('lib/conversation-ai/generate-replies.ts', 'utf8'),
  userSettings: readFileSync('lib/clapcheeks/user-settings.ts', 'utf8'),
  runtimeHealthLib: readFileSync('lib/clapcheeks/runtime-health.ts', 'utf8'),
  inboundWatcherHealthLib: readFileSync('lib/clapcheeks/inbound-watcher-health.ts', 'utf8'),
  healthRoute: readFileSync('app/api/health/route.ts', 'utf8'),
}

test('scheduled messages require approval and explicit send confirmation', () => {
  assert.match(files.scheduledRoute, /status: 'pending'/)
  assert.match(files.scheduledSendRoute, /confirm_send !== true/)
  assert.match(files.scheduledSendRoute, /live_send_phrase !== LIVE_SEND_PHRASE/)
  assert.match(files.scheduledSendRoute, /const LIVE_SEND_PHRASE = 'SEND LIVE TO JULIAN'/)
  assert.match(files.scheduledSendRoute, /validateLiveSendGate/)
  assert.match(files.scheduledSendRoute, /scheduled recipient does not match the live-send expected last4/)
  assert.match(files.scheduledSendRoute, /scheduled message body does not match the live-send preflight body/)
  assert.match(files.scheduledSendRoute, /redacted_execution_plan/)
  assert.match(files.scheduledSendRoute, /expected_body_sha256/)
  assert.match(files.scheduledSendRoute, /status: 423/)
  assert.match(files.scheduledSendRoute, /Type \$\{LIVE_SEND_PHRASE\} to send this scheduled message live/)
  assert.match(files.scheduledSendRoute, /Message must be approved before sending/)
  assert.match(files.scheduledSendRoute, /dry_run === true/)
  assert.match(files.scheduledSendRoute, /phone_last4/)
  assert.match(files.scheduledSendRoute, /message_length/)
  assert.match(files.scheduledSendRoute, /SEND_SOURCE_LABEL/)
  assert.match(files.scheduledSendRoute, /send_provenance/)
  assert.match(files.scheduledSendRoute, /request_id/)
  assert.match(files.scheduledSendRoute, /message_sha256/)
})

test('scheduled live send claims the row before transport to prevent duplicate retries', () => {
  assert.match(files.scheduledSendRoute, /LIVE_SEND_CLAIM_PREFIX = 'send_claim:'/)
  assert.match(files.scheduledSendRoute, /CLAIM_PROBE_PHRASE = 'PROBE CLAIM WITHOUT SENDING'/)
  assert.match(files.scheduledSendRoute, /acquireLiveSendLock/)
  assert.match(files.scheduledSendRoute, /claimLiveSend/)
  assert.match(files.scheduledSendRoute, /claim_probe_hold_ms/)
  assert.match(files.scheduledSendRoute, /Math\.min\(Math\.max\(Number\(body\.claim_probe_hold_ms\) \|\| 0, 0\), 1000\)/)
  assert.match(files.scheduledSendRoute, /claim_probe === true/)
  assert.match(files.scheduledSendRoute, /claim_probe_restored_no_send/)
  assert.match(files.scheduledSendRoute, /reason: 'existing_claim'/)
  assert.match(files.scheduledSendRoute, /no_live_send_performed: true/)
  assert.match(files.scheduledSendRoute, /status: 'rejected', rejection_reason: rejectionReason/)
  assert.match(files.scheduledSendRoute, /This scheduled message is already being sent/)
  assert.match(files.scheduledSendRoute, /no_send_performed: true/)
  assert.match(files.scheduledSendRoute, /row was claimed before transport to prevent duplicate retries/)
  assert.ok(
    files.scheduledSendRoute.indexOf('const claim = await claimLiveSend') <
      files.scheduledSendRoute.indexOf('const { stdout, stderr } = await execFileAsync'),
  )
})

test('scheduled live send verifies immediate iMessage delivery through local Messages DB', () => {
  assert.match(files.scheduledSendRoute, /verifyImmediateSendInMessages/)
  assert.match(files.scheduledSendRoute, /Library\/Messages\/chat\.db/)
  assert.match(files.scheduledSendRoute, /Messages DB verification failed/)
  assert.match(files.scheduledSendRoute, /messages_db_verification/)
  assert.match(files.scheduledSendRoute, /execFileAsync/)
  assert.doesNotMatch(files.scheduledSendRoute, /exec\(/)
  assert.match(files.scheduledSendRoute, /and m\.text like/)
  assert.match(files.scheduledSendRoute, /and \$\{normalizedHandle\} like/)
})

test('scheduled delete is a safe cancel, not an unmapped hard delete', () => {
  assert.match(files.scheduledItemRoute, /deleted_from_dashboard/)
  assert.match(files.scheduledItemRoute, /status: 'failed'/)
  assert.doesNotMatch(files.scheduledItemRoute, /\.delete\(\)/)
  assert.match(files.compat, /kind === "delete" && mapped === "outbound_scheduled_messages"/)
  assert.match(files.compat, /outbound:markFailed/)
})

test('scheduled dashboard has mobile-friendly quick-view controls', () => {
  assert.match(files.scheduledPage, /flex flex-col gap-4 sm:flex-row/)
  assert.match(files.scheduledPage, /w-full sm:w-auto/)
  assert.match(files.scheduledPage, /grid grid-cols-2 gap-2 sm:flex sm:flex-col/)
  assert.match(files.scheduledPage, /Cancel this scheduled message/)
  assert.match(files.scheduledPage, /aria-label="Cancel scheduled message"/)
  assert.match(files.scheduledPage, /placeholder="Type SEND LIVE TO JULIAN"/)
  assert.match(files.scheduledPage, /live_send_phrase: sendPhrase\.trim\(\)/)
  assert.match(files.scheduledPage, /useSearchParams/)
  assert.match(files.scheduledPage, /FILTERS/)
  assert.match(files.scheduledPage, /searchParams\.get\('filter'\)/)
  assert.match(files.scheduledPage, /status=\$\{listStatus\}&limit=200/)
  assert.match(files.scheduledPage, /status=all&limit=200/)
  assert.match(files.scheduledPage, /setCountMessages/)
})

test('scheduled dashboard clears stale errors before successful actions', () => {
  assert.match(files.scheduledPage, /async function submitCompose\(\) \{\s*setError\(null\)/)
  assert.match(files.scheduledPage, /else \{\s*setError\(null\)\s*setShowCompose\(false\)/)
  assert.match(files.scheduledPage, /async function approve\(id: string\) \{\s*setError\(null\)/)
  assert.match(files.scheduledPage, /async function sendNow\(id: string\) \{\s*setError\(null\)/)
  assert.match(files.scheduledPage, /async function deleteMsg\(id: string\) \{[\s\S]*setError\(null\)/)
})

test('intelligence insights fall back to the Convex-backed analytics summary', () => {
  assert.match(files.intelligencePage, /statsFromAnalytics/)
  assert.match(files.intelligencePage, /const canFetchApiBase = Boolean\(apiBase && token\)/)
  assert.match(files.intelligencePage, /\/api\/analytics\/summary\?days=30/)
  assert.match(files.intelligencePage, /setStats\(statsFromAnalytics/)
  assert.match(files.intelligencePage, /setAbTest\(\{ styles: \[\], winner: null \}\)/)
})

test('dashboard briefing uses Convex-backed conversations for stale-convo count', () => {
  assert.match(files.compat, /clapcheeks_conversations: "conversations:listForUser"/)
  assert.match(files.briefingCard, /\.from\('clapcheeks_conversations'\)/)
  assert.match(files.briefingCard, /\.lt\('last_message_at', fortyEightHoursAgo\)/)
  assert.match(files.briefingCard, /missing_required_services/)
  assert.match(files.briefingCard, /tokenBlockers/)
  assert.match(files.briefingCard, /All required tokens configured/)
  assert.match(files.briefingCard, /getInboundWatcherHealth/)
  assert.match(files.briefingCard, /Runtime Blockers/)
  assert.match(files.briefingCard, /Inbound watcher healthy/)
})

test('roster thumbnails load eagerly inside scrollable kanban columns', () => {
  assert.match(files.rosterCard, /loading="eager"/)
  assert.match(files.dailyTopThree, /loading="eager"/)
})

test('communications console connects dashboard navigation to gated draft replies', () => {
  assert.match(files.appSidebar, /href: '\/communications'/)
  assert.match(files.dashboardPage, /href="\/communications"/)
  assert.match(files.communicationsPage, /TARGET_PLATFORMS/)
  assert.match(files.communicationsPage, /\.from\('clapcheeks_conversations'\)/)
  assert.match(files.communicationsPage, /redirect\('\/auth\/login'\)/)
  assert.match(files.communicationsPage, /isDisplayableCommunicationThread/)
  assert.match(files.communicationsPage, /name === 'hinge chat'/)
  assert.match(files.communicationsPage, /hasMessage \|\| !isGenericTransportName/)
  assert.match(files.communicationsConsole, /\/api\/conversation\/suggest/)
  assert.match(files.communicationsConsole, /\/api\/autonomy-config/)
  assert.match(files.communicationsConsole, /auto_respond_enabled/)
  assert.match(files.communicationsConsole, /Drafts stay approval gated/)
})

test('reply drafting degrades gracefully when Anthropic is unavailable', () => {
  assert.match(files.replyGenerator, /ANTHROPIC_REPLY_MODEL/)
  assert.match(files.replyGenerator, /buildFallbackReplies/)
  assert.match(files.replyGenerator, /storeReplySuggestions/)
  assert.match(files.replyGenerator, /if \(!anthropicApiKey\)/)
  assert.match(files.userSettings, /\.clapcheeks-local/)
})

test('Convex read rows expose legacy id fields used by dashboard links and keys', () => {
  assert.match(files.compat, /function normalizeReadRow/)
  assert.match(files.compat, /next\.id == null && row\._id != null/)
  assert.match(files.compat, /next\.id = row\._id/)
  assert.match(files.compat, /normalizePayload\(data\)/)
})

test('dashboard iMessage self-test is dry-run first and live sends require confirmation', () => {
  assert.match(files.imessageTestRoute, /dry_run === true/)
  assert.match(files.imessageTestRoute, /Explicit live-send confirmation required/)
  assert.match(files.imessageTestRoute, /confirm_send !== true/)
  assert.match(files.imessageTestRoute, /live_send_phrase !== LIVE_SEND_PHRASE/)
  assert.match(files.imessageTestRoute, /const LIVE_SEND_PHRASE = 'SEND LIVE TO JULIAN'/)
  assert.match(files.imessageTestRoute, /CLAPCHEEKS_SELF_TEST_PHONE/)
  assert.match(files.imessageTestRoute, /LIVE_SEND_ENV/)
  assert.match(files.imessageTestRoute, /LIVE_SEND_PREFLIGHT_PATH/)
  assert.match(files.imessageTestRoute, /LIVE_SEND_PREFLIGHT_MAX_AGE_SECONDS/)
  assert.match(files.imessageTestRoute, /liveSendPreflightMetadata/)
  assert.match(files.imessageTestRoute, /live-send preflight evidence is stale/)
  assert.match(files.imessageTestRoute, /liveSendGateMetadata/)
  assert.match(files.imessageTestRoute, /validateLiveSendRequest/)
  assert.match(files.imessageTestRoute, /message body does not match the live-send preflight body/)
  assert.match(files.imessageTestRoute, /status: 423/)
  assert.match(files.imessageTestRoute, /CLAPCHEEKS_LIVE_SEND_PERMISSION/)
  assert.match(files.imessageTestRoute, /process\.env\.CLAPCHEEKS_LIVE_SEND_PERMISSION !== LIVE_SEND_PHRASE/)
  assert.match(files.imessageTestRoute, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.imessageTestRoute, /SAMPLE_2944_OVERRIDE_PHRASE = 'I CONFIRM 757-831-2944 IS THE LIVE DESTINATION'/)
  assert.match(files.imessageTestRoute, /configured live-send phone does not match expected last4/)
  assert.match(files.imessageTestRoute, /redacted_execution_plan/)
  assert.match(files.imessageTestRoute, /body_sha256/)
  assert.match(files.imessageTestRoute, /createHash/)
  assert.doesNotMatch(files.imessageTestRoute, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944 !== 'true'/)
  assert.match(files.imessageTestRoute, /live_send_gate/)
  assert.match(files.imessageTestPanel, /useState\(true\)/)
  assert.match(files.imessageTestPanel, /dry_run: dryRun/)
  assert.match(files.imessageTestPanel, /confirm_send: !dryRun && confirmLiveSend/)
  assert.match(files.imessageTestPanel, /live_send_phrase: liveSendPhrase\.trim\(\)/)
  assert.match(files.imessageTestPanel, /Use self-test/)
  assert.match(files.imessageTestPanel, /Type \$\{requiredLivePhrase\}/)
  assert.match(files.imessageTestPanel, /liveSendLocked/)
  assert.match(files.imessageTestPanel, /Live iMessage queueing is locked/)
  assert.match(files.imessageTestPanel, /destination and message body/)
  assert.match(files.imessageTestPanel, /Final live-send gate/)
  assert.match(files.imessageTestPanel, /Preflight freshness/)
  assert.match(files.imessageTestPanel, /liveSendGate\.preflight/)
  assert.match(files.imessageTestPanel, /required_permission/)
  assert.match(files.imessageTestPanel, /liveSendGate\.runbook/)
  assert.match(files.imessageTestPanel, /Verify Test iMessage/)
  assert.match(files.imessageTestPanel, /Send Live Test iMessage/)
})

test('repeatable visual E2E verifier covers dashboard mobile, scheduled mobile, modal, and insights', () => {
  assert.match(files.packageJson, /"test:e2e:browser": "\.\/scripts\/e2e-browser-visual-safe\.sh"/)
  assert.match(files.browserVisualScript, /CLAPCHEEKS_BROWSER_USE_CCT/)
  assert.match(files.browserVisualScript, /e2e-browser-visual-cct\.mjs/)
  assert.match(files.browserVisualCctScript, /CCT Chrome via CDP/)
  assert.match(files.browserVisualCctScript, /scheduled_send_confirmation_guardrail/)
  assert.match(files.browserVisualCctScript, /mobile_metrics_overflow_free/)
  assert.match(files.browserVisualCctScript, /no_live_send_performed/)
  assert.match(files.browserVisualScript, /dashboard desktop/)
  assert.match(files.browserVisualScript, /dashboard navigation integrity/)
  assert.match(files.browserVisualScript, /dashboard health blockers quick view/)
  assert.match(files.browserVisualScript, /dashboard-health-blockers-proof\.json/)
  assert.match(files.browserVisualScript, /dashboard_health_blockers_quick_view/)
  assert.match(files.browserVisualScript, /runtime_tile_present/)
  assert.match(files.browserVisualScript, /runtime_blocker_present/)
  assert.match(files.browserVisualScript, /tcc shows python full disk access is off/)
  assert.match(files.browserVisualScript, /no_token_values_present/)
  assert.match(files.browserVisualScript, /dashboard-navigation-proof\.json/)
  assert.match(files.browserVisualScript, /dashboard_navigation_integrity/)
  assert.match(files.browserVisualScript, /dashboard imessage self-test dry-run surface/)
  assert.match(files.browserVisualScript, /dashboard-imessage-self-test-proof\.json/)
  assert.match(files.browserVisualScript, /dashboard_imessage_self_test_surface/)
  assert.match(files.browserVisualScript, /live_send_gate_present/)
  assert.match(files.browserVisualScript, /live_send_gate_no_send/)
  assert.match(files.browserVisualScript, /live_send_gate_preflight_fresh/)
  assert.match(files.browserVisualScript, /Preflight freshness/)
  assert.match(files.browserVisualScript, /live_send_gate_redacted_plan_present/)
  assert.match(files.browserVisualScript, /live_send_gate_raw_phone_absent/)
  assert.match(files.browserVisualScript, /live_send_gate_raw_body_absent/)
  assert.match(files.browserVisualScript, /dashboard imessage dry-run click/)
  assert.match(files.browserVisualScript, /dashboard-imessage-dry-run-click-proof\.json/)
  assert.match(files.browserVisualScript, /dashboard_imessage_dry_run_click/)
  assert.match(files.browserVisualScript, /no_queue_delta/)
  assert.match(files.browserVisualScript, /dry_run_default/)
  assert.match(files.browserVisualScript, /Verify Test iMessage/)
  assert.match(files.browserVisualScript, /Draft date ask/)
  assert.match(files.browserVisualScript, /Review scheduled/)
  assert.match(files.browserVisualScript, /no_click_performed/)
  assert.match(files.browserVisualScript, /dashboard mobile quick view/)
  assert.match(files.browserVisualScript, /dashboard-mobile-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /dashboard_mobile_quick_view/)
  assert.match(files.browserVisualScript, /device mobile runtime safety/)
  assert.match(files.browserVisualScript, /device inbound watcher TCC proof/)
  assert.match(files.browserVisualScript, /device-control-safety-proof\.json/)
  assert.match(files.browserVisualScript, /device-mobile-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /device_mobile_quick_view/)
  assert.match(files.browserVisualScript, /device_control_safety_surface/)
  assert.match(files.browserVisualScript, /Physical PNG proof must pass/)
  assert.match(files.browserVisualScript, /Inbound watcher unblock/)
  assert.match(files.browserVisualScript, /TCC python:/)
  assert.match(files.browserVisualScript, /Full Disk Access TCC:/)
  assert.match(files.browserVisualScript, /repair-inbound-watcher-fda\.sh/)
  assert.match(files.browserVisualScript, /open-inbound-watcher-fda-settings\.sh/)
  assert.match(files.browserVisualScript, /repair_verify_command_present/)
  assert.match(files.browserVisualScript, /tech\.clapcheeks\.inbound-watcher/)
  assert.match(files.browserVisualScript, /npm run test:e2e:runtime/)
  assert.match(files.browserVisualScript, /terminal_proof_ok/)
  assert.match(files.browserVisualScript, /tcc_python_authorized/)
  assert.match(files.browserVisualScript, /tcc_python_denied_or_off/)
  assert.match(files.browserVisualScript, /Queue observe/)
  assert.match(files.browserVisualScript, /no_live_action_performed/)
  assert.match(files.browserVisualScript, /scheduled mobile quick view/)
  assert.match(files.browserVisualScript, /scheduled api-bound cards hydrated/)
  assert.match(files.browserVisualScript, /scheduled_api_binding_ready_js/)
  assert.match(files.browserVisualScript, /scheduled ui api-bound values/)
  assert.match(files.browserVisualScript, /scheduled-api-binding-proof\.json/)
  assert.match(files.browserVisualScript, /scheduled_ui_matches_api/)
  assert.match(files.browserVisualScript, /scheduled_api_binding/)
  assert.match(files.browserVisualScript, /counts_match/)
  assert.match(files.browserVisualScript, /scheduled mobile modal/)
  assert.match(files.browserVisualScript, /scheduled mobile form fill no-send/)
  assert.match(files.browserVisualScript, /scheduled-mobile-form-proof\.json/)
  assert.match(files.browserVisualScript, /scheduled_mobile_form_filled/)
  assert.match(files.browserVisualScript, /scheduled_mobile_form_no_submit/)
  assert.match(files.browserVisualScript, /Safe mobile compose proof only\. Do not send\./)
  assert.match(files.browserVisualScript, /scheduled send confirmation guardrails/)
  assert.match(files.browserVisualScript, /\/scheduled\?filter=approved/)
  assert.match(files.browserVisualScript, /scheduled-send-confirmation-guardrail-proof\.json/)
  assert.match(files.browserVisualScript, /scheduled-send-confirmation-modal-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /scheduled-send-confirmation-modal-metrics\.json/)
  assert.match(files.browserVisualScript, /scheduled_send_confirmation_guardrail/)
  assert.match(files.browserVisualScript, /Safe E2E Browser Guardrail 2944/)
  assert.match(files.browserVisualScript, /SEND SAFE/)
  assert.match(files.browserVisualScript, /intelligence desktop/)
  assert.match(files.browserVisualScript, /intelligence api-bound values/)
  assert.match(files.browserVisualScript, /intelligence-api-binding-proof\.json/)
  assert.match(files.browserVisualScript, /intelligence_ui_matches_api/)
  assert.match(files.browserVisualScript, /intelligence_api_binding/)
  assert.match(files.browserVisualScript, /intelligence mobile quick view/)
  assert.match(files.browserVisualScript, /intelligence-mobile-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /intelligence_mobile_quick_view/)
  assert.match(files.browserVisualScript, /analytics mobile quick view/)
  assert.match(files.browserVisualScript, /analytics-mobile-api-binding-proof\.json/)
  assert.match(files.browserVisualScript, /analytics-mobile-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /analytics_mobile_ui_matches_api/)
  assert.match(files.browserVisualScript, /analytics_mobile_api_binding/)
  assert.match(files.browserVisualScript, /seq 1 60/)
  assert.match(files.browserVisualScript, /This page could not be found/)
  assert.match(files.browserVisualScript, /failed-\$\{failure_name\}-2026-05-18\.png/)
  assert.match(files.browserVisualScript, /no_live_send_performed/)
  assert.match(files.browserVisualScript, /\/api\/analytics\/summary\?days=30/)
  assert.match(files.browserVisualScript, /\/api\/imessage\/test/)
})

test('completion audit keeps real live send as an explicit unproved gate', () => {
  assert.match(files.packageJson, /"test:e2e:audit": "node scripts\/e2e-completion-audit\.mjs"/)
  assert.match(files.completionAuditScript, /dashboard works end to end/)
  assert.match(files.completionAuditScript, /required E2E evidence artifacts are fresh/)
  assert.match(files.completionAuditScript, /CLAPCHEEKS_EVIDENCE_MAX_AGE_SECONDS/)
  assert.match(files.completionAuditScript, /staleArtifacts/)
  assert.match(files.completionAuditScript, /dashboard_navigation_integrity/)
  assert.match(files.completionAuditScript, /dashboard_navigation/)
  assert.match(files.completionAuditScript, /dashboard_imessage_self_test_surface/)
  assert.match(files.completionAuditScript, /dashboard_imessage_self_test/)
  assert.match(files.completionAuditScript, /dashboard_imessage_dry_run_click/)
  assert.match(files.completionAuditScript, /dashboard_imessage_dry_run/)
  assert.match(files.completionAuditScript, /dashboard_mobile_quick_view/)
  assert.match(files.completionAuditScript, /device_mobile_quick_view/)
  assert.match(files.completionAuditScript, /device_control_safety_surface/)
  assert.match(files.completionAuditScript, /device_control_status/)
  assert.match(files.completionAuditScript, /scheduled_mobile_form_filled/)
  assert.match(files.completionAuditScript, /scheduled_ui_matches_api/)
  assert.match(files.completionAuditScript, /scheduled_api_binding/)
  assert.match(files.completionAuditScript, /scheduled_mobile_form_no_submit/)
  assert.match(files.completionAuditScript, /scheduled_mobile_form/)
  assert.match(files.completionAuditScript, /scheduled_send_confirmation_guardrail/)
  assert.match(files.completionAuditScript, /send_disabled_with_wrong_phrase/)
  assert.match(files.completionAuditScript, /intelligence_ui_matches_api/)
  assert.match(files.completionAuditScript, /intelligence_api_binding/)
  assert.match(files.completionAuditScript, /intelligence_mobile_quick_view/)
  assert.match(files.completionAuditScript, /analytics_mobile_quick_view/)
  assert.match(files.completionAuditScript, /analytics_mobile_ui_matches_api/)
  assert.match(files.completionAuditScript, /analytics_mobile_api_binding/)
  assert.match(files.completionAuditScript, /runtime inbound source of truth is reachable in no-send mode/)
  assert.match(files.completionAuditScript, /scripts\/repair-inbound-watcher-fda\.sh/)
  assert.match(files.completionAuditScript, /Current blocker:/)
  assert.match(files.completionAuditScript, /local Chrome browser proof from Julian computer is current and read-only/)
  assert.match(files.completionAuditScript, /CLAPCHEEKS_LOCAL_BROWSER_PROOF/)
  assert.match(files.completionAuditScript, /chrome\?\.active_route === '\/analytics'/)
  assert.match(files.completionAuditScript, /forbidden_fixture_present === false/)
  assert.match(files.completionAuditScript, /insights are functional/)
  assert.match(files.completionAuditScript, /scheduled message create approve dry-run cancel path works/)
  assert.match(files.completionAuditScript, /scheduledDryRunProvenance/)
  assert.match(files.completionAuditScript, /dry_run_provenance_ok/)
  assert.match(files.completionAuditScript, /scheduled fixture cleanup/)
  assert.match(files.completionAuditScript, /mobile quick-view UX works/)
  assert.match(files.completionAuditScript, /safe sample 757-831-2944 used without accidental real outbound send/)
  assert.match(files.completionAuditScript, /real outbound send-to-Julian test/)
  assert.match(files.completionAuditScript, /unproved_requires_explicit_live_permission/)
  assert.match(files.completionAuditScript, /safe_to_continue_without_live_send/)
  assert.match(files.completionAuditScript, /final_gate/)
  assert.match(files.completionAuditScript, /next_required_action/)
  assert.match(files.completionAuditScript, /Next required action:/)
  assert.match(files.completionAuditScript, /Final gate blockers:/)
  assert.match(files.completionAuditScript, /Get current explicit live-send approval/)
  assert.match(files.completionAuditScript, /livePreflightEvidencePath/)
  assert.match(files.completionAuditScript, /liveEvidenceMatchesPreflight/)
  assert.match(files.completionAuditScript, /body_hash_match/)
  assert.match(files.completionAuditScript, /body_length_match/)
  assert.match(files.completionAuditScript, /destination_last4_match/)
  assert.match(files.completionAuditScript, /send_provenance_verified/)
  assert.match(files.completionAuditScript, /clapcheeks_scheduled_messages_send_api/)
})

test('safe readiness verifier cancels leftover active scheduled test fixtures', () => {
  assert.match(files.safeReadinessScript, /verifyNoActiveTestFixtures/)
  assert.match(files.safeReadinessScript, /Safe E2E Readiness/)
  assert.match(files.safeReadinessScript, /Safe E2E Browser Guardrail/)
  assert.match(files.safeReadinessScript, /Live Send Evidence/)
  assert.match(files.safeReadinessScript, /\/api\/scheduled-messages\?status=\$\{status\}&limit=200/)
  assert.match(files.safeReadinessScript, /method: 'DELETE'/)
  assert.match(files.safeReadinessScript, /scheduled fixture cleanup/)
  assert.match(files.safeReadinessScript, /active fixtures=/)
  assert.match(files.safeReadinessScript, /redacted_execution_plan/)
  assert.match(files.safeReadinessScript, /Safe E2E scheduled dry-run only/)
})

test('safe readiness verifier checks core dashboard route matrix', () => {
  assert.match(files.safeReadinessScript, /CLAPCHEEKS_SAFE_E2E_USE_CCT/)
  assert.match(files.safeReadinessScript, /CCT tab did not expose a debugger URL/)
  assert.match(files.safeReadinessScript, /credentials: 'include'/)
  assert.match(files.safeReadinessScript, /coreRoutes/)
  assert.match(files.safeReadinessScript, /snippets/)
  assert.match(files.safeReadinessScript, /\/dashboard\/matches/)
  assert.match(files.safeReadinessScript, /\/dashboard\/roster/)
  assert.match(files.safeReadinessScript, /\/dashboard\/content-library/)
  assert.match(files.safeReadinessScript, /\/conversation/)
  assert.match(files.safeReadinessScript, /\/device/)
  assert.match(files.safeReadinessScript, /Every match/)
  assert.match(files.safeReadinessScript, /Runtime readiness/)
  assert.match(files.safeReadinessScript, /Drop photos here/)
  assert.match(files.safeReadinessScript, /60\/20\/10\/10/)
  assert.match(files.safeReadinessScript, /missing/)
  assert.match(files.safeReadinessScript, /routes ok with content assertions/)
  assert.match(files.safeReadinessScript, /dashboard core route matrix/)
  assert.match(files.completionAuditScript, /dashboard core route matrix/)
  assert.match(files.completionAuditScript, /coreRouteFailures/)
  assert.match(files.completionAuditScript, /route_matrix_summary/)
})

test('safe readiness verifier checks analytics insights contract', () => {
  assert.match(files.safeReadinessScript, /function verifyAnalyticsSummaryContract/)
  assert.match(files.safeReadinessScript, /analytics summary contract/)
  assert.match(files.safeReadinessScript, /requiredTotals/)
  assert.match(files.safeReadinessScript, /requiredFunnelStages/)
  assert.match(files.safeReadinessScript, /Conversations/)
  assert.match(files.safeReadinessScript, /conversationsConsistent/)
  assert.match(files.safeReadinessScript, /platformRowsValid/)
  assert.match(files.safeReadinessScript, /timeSeriesValid/)
  assert.match(files.safeReadinessScript, /dataQualityValid/)
  assert.match(files.safeReadinessScript, /rizzValid/)
  assert.match(files.completionAuditScript, /analytics summary contract/)
  assert.match(files.completionAuditScript, /analytics_contract/)
})

test('safe readiness verifier checks dashboard runtime health contract without leaking tokens', () => {
  assert.match(files.safeReadinessScript, /function verifyDashboardHealthContract/)
  assert.match(files.safeReadinessScript, /dashboard runtime health contract/)
  assert.match(files.safeReadinessScript, /\/api\/health\?detailed=true/)
  assert.match(files.safeReadinessScript, /\/api\/agent\/token-health/)
  assert.match(files.safeReadinessScript, /missingServices/)
  assert.match(files.safeReadinessScript, /convexService\?\.status !== 'down'/)
  assert.match(files.safeReadinessScript, /inboundWatcherService\?\.status !== 'down'/)
  assert.match(files.safeReadinessScript, /TCC shows Python Full Disk Access is off/)
  assert.match(files.safeReadinessScript, /inbound_watcher_status/)
  assert.match(files.safeReadinessScript, /missingPlatformRows/)
  assert.match(files.safeReadinessScript, /missingRequiredServices/)
  assert.match(files.safeReadinessScript, /missing_required_services/)
  assert.match(files.safeReadinessScript, /token_values_omitted/)
  assert.match(files.safeReadinessScript, /not a full backend schema\/index doctor/)
  assert.match(files.completionAuditScript, /dashboard runtime health contract/)
  assert.match(files.completionAuditScript, /runtime_health_contract/)
  assert.match(files.tokenHealthRoute, /Token values are intentionally omitted/)
  assert.match(files.tokenHealthLib, /missing_required/)
  assert.match(files.tokenHealthLib, /missing_required_services/)
  assert.match(files.tokenHealthLib, /SendBird missing/)
  assert.match(files.tokenHealthLib, /runtime\.sendbird_status/)
  assert.match(files.tokenHealthLib, /telemetry:listEventsForUser/)
  assert.match(files.tokenHealthLib, /limit: 10/)
  assert.match(files.tokenHealthLib, /selectFreshConfiguredSendBirdReadiness/)
  assert.match(files.tokenHealthLib, /capture_status/)
  assert.match(files.tokenHealthLib, /waiting_for_hinge_chat/)
  assert.match(files.tokenHealthLib, /Hinge proxy is running and waiting for chat capture/)
  assert.match(files.tokenHealthLib, /defaultTelemetryUserId/)
  assert.match(files.tokenHealthLib, /fleet-julian/)
  assert.match(files.tokenHealthLib, /convex\.telemetry/)
  assert.match(files.healthRoute, /runHealthChecks/)
  assert.match(files.healthRoute, /detailed/)
  assert.match(files.healthRoute, /signed-in dashboard users can read detailed health/)
  assert.match(files.healthRoute, /createClient/)
  assert.match(files.healthRoute, /convex\.auth\.getUser/)
  assert.match(files.healthRoute, /detailed && !shouldLog/)
  assert.match(files.healthRoute, /health\.overall === 'healthy'/)
  assert.match(files.healthRoute, /503/)
  const monitoringHealth = readFileSync('lib/monitoring/health.ts', 'utf8')
  assert.match(monitoringHealth, /checkInboundWatcher/)
  assert.match(monitoringHealth, /service: 'inbound-watcher'/)
  assert.match(monitoringHealth, /getInboundWatcherHealth/)
  assert.match(files.inboundWatcherHealthLib, /runtime\.inbound_watcher_status/)
  assert.match(files.inboundWatcherHealthLib, /telemetry:listEventsForUser/)
  assert.match(files.inboundWatcherHealthLib, /REMOTE_STALE_MS/)
  assert.match(files.runtimeHealthLib, /inbound-watcher-status\.json/)
  assert.match(files.runtimeHealthLib, /fda_alert_imessage_enabled/)
  assert.match(files.runtimeHealthLib, /Full Disk Access missing for launchd Python/)
  assert.match(files.runtimeHealthLib, /status_missing/)
  assert.match(files.runtimeHealthLib, /terminal_read_proof/)
  assert.match(files.runtimeHealthLib, /CLAPCHEEKS_INBOUND_TERMINAL_PROOF/)
  assert.match(files.runtimeHealthLib, /Terminal read-only proof passed/)
  assert.match(files.runtimeHealthLib, /CLAPCHEEKS_INBOUND_REPAIR_EVIDENCE/)
  assert.match(files.runtimeHealthLib, /full_disk_access_tcc/)
  assert.match(files.runtimeHealthLib, /TCC shows Python Full Disk Access is off/)
  assert.match(files.runtimeHealthLib, /python_authorized/)
  assert.match(files.runtimeHealthLib, /python_denied_or_off/)
  assert.match(files.runtimeHealthLib, /raw_handles_written/)
})

test('safe readiness verifier checks iMessage live-send gate metadata is validated and redacted', () => {
  assert.match(files.safeReadinessScript, /redacted_execution_plan_present/)
  assert.match(files.safeReadinessScript, /body_sha256_present/)
  assert.match(files.safeReadinessScript, /CLAPCHEEKS_LIVE_SEND_PERMISSION/)
  assert.match(files.safeReadinessScript, /Safe ClapCheeks no-send preflight for 757 sample/)
  assert.match(files.safeReadinessScript, /live_send_gate/)
})

test('safe readiness verifier checks Messages DB read-only for the sample number without logging content', () => {
  assert.match(files.safeReadinessScript, /verifyMessagesDbReadOnly/)
  assert.match(files.safeReadinessScript, /Library\/Messages\/chat\.db/)
  assert.match(files.safeReadinessScript, /sqlite3/)
  assert.match(files.safeReadinessScript, /-readonly/)
  assert.match(files.safeReadinessScript, /messages db read-only sample lookup/)
  assert.match(files.safeReadinessScript, /content_logged: false/)
  assert.match(files.safeReadinessScript, /async function retry/)
  assert.match(files.safeReadinessScript, /attempts/)
  assert.match(files.safeReadinessScript, /stderr/)
  assert.match(files.completionAuditScript, /messages db read-only sample lookup/)
  assert.match(files.completionAuditScript, /messages_db_read_only/)
})

test('safe readiness verifier retries transient Next cold-compile dynamic route errors', () => {
  assert.match(files.safeReadinessScript, /jsonFetchRetryColdCompile/)
  assert.match(files.safeReadinessScript, /looksLikeNextColdCompileError/)
  assert.match(files.safeReadinessScript, /<!DOCTYPE html>/)
  assert.match(files.safeReadinessScript, /\/api\/scheduled-messages\/\$\{id\}/)
  assert.match(files.safeReadinessScript, /method: 'PATCH'/)
})

test('live-send evidence harness refuses without explicit destination body and permission', () => {
  assert.match(files.packageJson, /"test:e2e:live": "node scripts\/e2e-live-send-evidence\.mjs"/)
  assert.match(files.liveSendEvidenceScript, /SEND LIVE TO JULIAN/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_PHONE/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_BODY/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_EXPECTED_LAST4/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.liveSendEvidenceScript, /I CONFIRM 757-831-2944 IS THE LIVE DESTINATION/)
  assert.match(files.liveSendEvidenceScript, /safe sample 2944 requires explicit sample-destination override/)
  assert.match(files.liveSendEvidenceScript, /refused: true/)
  assert.match(files.liveSendEvidenceScript, /live_send_performed: false/)
  assert.match(files.liveSendEvidenceScript, /messages_db_verified/)
  assert.match(files.liveSendEvidenceScript, /createHash/)
  assert.match(files.liveSendEvidenceScript, /message_sha256/)
  assert.match(files.liveSendEvidenceScript, /send_provenance_verified/)
  assert.match(files.liveSendEvidenceScript, /send_provenance/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_PREFLIGHT/)
  assert.match(files.liveSendEvidenceScript, /matching live-send preflight evidence is required/)
  assert.match(files.liveSendEvidenceScript, /preflight body SHA-256 does not match current body/)
  assert.match(files.liveSendEvidenceScript, /CLAPCHEEKS_LIVE_SEND_PREFLIGHT_MAX_AGE_SECONDS/)
  assert.match(files.liveSendEvidenceScript, /preflight is stale/)
  assert.match(files.liveSendEvidenceScript, /live_send_phrase: 'SEND LIVE TO JULIAN'/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses before network calls when env is missing/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses sample 2944 without explicit override/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses destination last4 mismatch/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses without matching preflight evidence/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses preflight body mismatch/)
  assert.match(files.liveSendEvidenceRefusalTest, /refuses stale preflight/)
  assert.match(files.liveSendEvidenceRefusalTest, /scheduled_message_id, undefined/)
})

test('live-send preflight validates final send inputs without mutating dashboard state', () => {
  assert.match(files.packageJson, /"test:e2e:live:preflight": "node scripts\/e2e-live-send-preflight\.mjs"/)
  assert.match(files.packageJson, /"test:e2e:live:sample-preflight": "node scripts\/e2e-live-send-sample-preflight\.mjs"/)
  assert.match(files.liveSendPreflightScript, /SEND LIVE TO JULIAN/)
  assert.match(files.liveSendPreflightScript, /CLAPCHEEKS_LIVE_SEND_PHONE/)
  assert.match(files.liveSendPreflightScript, /CLAPCHEEKS_LIVE_SEND_BODY/)
  assert.match(files.liveSendPreflightScript, /CLAPCHEEKS_LIVE_SEND_EXPECTED_LAST4/)
  assert.match(files.liveSendPreflightScript, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.liveSendPreflightScript, /I CONFIRM 757-831-2944 IS THE LIVE DESTINATION/)
  assert.match(files.liveSendPreflightScript, /sample_2944_override_required/)
  assert.match(files.liveSendPreflightScript, /no_send_performed: true/)
  assert.match(files.liveSendPreflightScript, /no_dashboard_mutation_performed: true/)
  assert.match(files.liveSendPreflightScript, /redacted_execution_plan/)
  assert.match(files.liveSendPreflightScript, /phone_redacted/)
  assert.match(files.liveSendPreflightScript, /createHash/)
  assert.match(files.liveSendPreflightScript, /message_sha256/)
  assert.match(files.liveSendPreflightScript, /required_env/)
  assert.match(files.liveSendPreflightScript, /extra_env_if_last4_2944/)
  assert.doesNotMatch(files.liveSendPreflightScript, /fetch\(/)
  assert.match(files.liveSendSamplePreflightScript, /Safe ClapCheeks no-send preflight for 757 sample/)
  assert.match(files.liveSendSamplePreflightScript, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.liveSendSamplePreflightScript, /raw sample body leaked into evidence/)
  assert.match(files.liveSendSamplePreflightScript, /raw sample phone leaked into evidence/)
  assert.match(files.liveSendSamplePreflightScript, /Sample live-send preflight: READY/)
  assert.match(files.liveSendPreflightExecTest, /live-send preflight refuses safely when live env is missing/)
  assert.match(files.liveSendPreflightExecTest, /live-send preflight requires explicit sample override for 757-831-2944/)
  assert.match(files.liveSendPreflightExecTest, /live-send preflight can become ready for a dummy non-sample destination without sending/)
  assert.match(files.liveSendPreflightExecTest, /no_send_performed/)
  assert.match(files.liveSendPreflightExecTest, /no_dashboard_mutation_performed/)
})

test('live-send approval packet makes final permission requirements explicit without sending', () => {
  assert.match(files.packageJson, /"test:e2e:live:approval-packet": "node scripts\/e2e-live-send-approval-packet\.mjs"/)
  assert.match(files.liveSendApprovalPacketScript, /CLAPCHEEKS_LIVE_SEND_APPROVAL_PACKET/)
  assert.match(files.liveSendApprovalPacketScript, /CLAPCHEEKS_LIVE_SEND_APPROVAL_PACKET_MD/)
  assert.match(files.liveSendApprovalPacketScript, /clapcheeks-live-send-approval-packet-2026-05-18\.json/)
  assert.match(files.liveSendApprovalPacketScript, /clapcheeks-live-send-approval-packet-2026-05-18\.md/)
  assert.match(files.liveSendApprovalPacketScript, /SEND LIVE TO JULIAN/)
  assert.match(files.liveSendApprovalPacketScript, /I CONFIRM 757-831-2944 IS THE LIVE DESTINATION/)
  assert.match(files.liveSendApprovalPacketScript, /exact_destination_phone_required: true/)
  assert.match(files.liveSendApprovalPacketScript, /exact_message_body_required: true/)
  assert.match(files.liveSendApprovalPacketScript, /approval_request_template/)
  assert.match(files.liveSendApprovalPacketScript, /raw_values_written: false/)
  assert.match(files.liveSendApprovalPacketScript, /Destination phone: <exact E\.164 phone number to send to>/)
  assert.match(files.liveSendApprovalPacketScript, /Message body: <exact text to send>/)
  assert.match(files.liveSendApprovalPacketScript, /No prior shell env from an older run is reused/)
  assert.match(files.liveSendApprovalPacketScript, /# ClapCheeks Live-Send Approval Packet/)
  assert.match(files.liveSendApprovalPacketScript, /Raw destination phone and raw message body are not written/)
  assert.match(files.liveSendApprovalPacketScript, /raw_phone_written: false/)
  assert.match(files.liveSendApprovalPacketScript, /raw_body_written: false/)
  assert.match(files.liveSendApprovalPacketScript, /operator_sequence/)
  assert.match(files.liveSendApprovalPacketScript, /npm run test:e2e:live:preflight/)
  assert.match(files.liveSendApprovalPacketScript, /npm run test:e2e:live/)
  assert.match(files.liveSendApprovalPacketScript, /local Chrome browser proof from Julian computer/)
  assert.match(files.liveSendApprovalPacketScript, /final live-send no-send rehearsal matches redacted preflight plan/)
  assert.match(files.liveSendApprovalPacketScript, /CLAPCHEEKS_LIVE_SEND_REHEARSAL/)
  assert.match(files.liveSendApprovalPacketScript, /live_send_rehearsal/)
  assert.match(files.liveSendApprovalPacketScript, /message_sha256_match/)
  assert.match(files.liveSendApprovalPacketScript, /destination_last4_match/)
  assert.match(files.liveSendApprovalPacketScript, /npm run test:e2e:live:rehearsal/)
  assert.match(files.readinessStatusScript, /rehearsal_ok/)
  assert.match(files.readinessStatusScript, /approval_template_present/)
  assert.match(files.readinessStatusScript, /markdown_exists/)
  assert.match(files.readinessStatusScript, /markdown_raw_e164_absent/)
  assert.match(files.readinessStatusScript, /markdown_raw_body_absent/)
  assert.match(files.readinessStatusScript, /markdown_sample_override_phrase_present/)
  assert.match(files.evidenceIndexScript, /approval_packet_rehearsal_ok/)
  assert.match(files.evidenceIndexScript, /approval_packet_template_present/)
  assert.match(files.evidenceIndexScript, /approval_packet_markdown/)
  assert.match(files.evidenceIndexScript, /approval_packet_markdown_raw_e164_absent/)
  assert.match(files.evidenceIndexScript, /approval_packet_markdown_raw_body_absent/)
  assert.match(files.evidenceIndexScript, /approval_packet_markdown_sample_override_present/)
  assert.match(files.evidenceIndexScript, /markdown_sample_override_phrase_present/)
  assert.doesNotMatch(files.liveSendApprovalPacketScript, /fetch\(/)
})

test('live-send evidence harness cleans up unverified created fixtures', () => {
  assert.match(files.liveSendEvidenceScript, /cancelUnsentFixture/)
  assert.match(files.liveSendEvidenceScript, /\/api\/scheduled-messages\/\$\{id\}/)
  assert.match(files.liveSendEvidenceScript, /method: 'DELETE'/)
  assert.match(files.liveSendEvidenceScript, /verified_sent/)
  assert.match(files.liveSendEvidenceScript, /cleanup/)
})

test('live-send runbook requires explicit Julian confirmation and evidence before completion', () => {
  assert.match(files.liveSendRunbook, /Destination phone number/)
  assert.match(files.liveSendRunbook, /Exact message body/)
  assert.match(files.liveSendRunbook, /Permission to perform one live send/)
  assert.match(files.liveSendRunbook, /SEND LIVE TO JULIAN/)
  assert.match(files.liveSendRunbook, /test:e2e:live:preflight/)
  assert.match(files.liveSendRunbook, /No send performed: true/)
  assert.match(files.liveSendRunbook, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.liveSendRunbook, /I CONFIRM 757-831-2944 IS THE LIVE DESTINATION/)
  assert.match(files.liveSendRunbook, /Do not use `757-831-2944`/)
  assert.match(files.liveSendRunbook, /messages_db_verified: true/)
  assert.match(files.liveSendRunbook, /validation\.message_sha256/)
  assert.match(files.liveSendRunbook, /message_sha256/)
  assert.match(files.liveSendRunbook, /raw message body is not written/)
  assert.match(files.liveSendRunbook, /rejects preflight evidence older than 900 seconds/)
  assert.match(files.liveSendRunbook, /CLAPCHEEKS_LIVE_SEND_PREFLIGHT_MAX_AGE_SECONDS/)
  assert.match(files.liveSendRunbook, /Only then mark the persistent goal complete/)
})

test('one-command safe readiness suite runs all non-live E2E gates', () => {
  assert.match(files.packageJson, /"test:e2e:readiness": "\.\/scripts\/e2e-readiness-all-safe\.sh"/)
  assert.match(files.readinessAllScript, /does not perform a live outbound send/)
  assert.match(files.readinessAllScript, /npm run test:e2e:browser/)
  assert.match(files.readinessAllScript, /npm run test:e2e:safe/)
  assert.match(files.readinessAllScript, /npm run test:e2e:runtime/)
  assert.match(files.readinessAllScript, /npm run test:e2e:local-browser/)
  assert.match(files.readinessAllScript, /npm run test:e2e:live:preflight/)
  assert.match(files.readinessAllScript, /npm run test:e2e:live:sample-preflight/)
  assert.match(files.readinessAllScript, /npm run test:e2e:live:rehearsal/)
  assert.match(files.readinessAllScript, /PREFLIGHT_STATUS/)
  assert.match(files.readinessAllScript, /no_send_performed/)
  assert.match(files.readinessAllScript, /no_dashboard_mutation_performed/)
  assert.match(files.readinessAllScript, /refused safely/)
  assert.match(files.readinessAllScript, /npm run test:e2e:live/)
  assert.match(files.readinessAllScript, /npm run test:e2e:audit/)
  assert.match(files.readinessAllScript, /npm run test:e2e:live:approval-packet/)
  assert.match(files.readinessAllScript, /npm run test:e2e:evidence/)
  assert.match(files.readinessAllScript, /CLAPCHEEKS_SELF_TEST_PHONE=\+17578312944/)
})

test('live-send rehearsal drives the preflight plan through scheduled dry-run without sending', () => {
  assert.match(files.liveSendRehearsalScript, /CLAPCHEEKS_LIVE_SEND_REHEARSAL_USE_CCT/)
  assert.match(files.liveSendRehearsalScript, /CCT tab did not expose a debugger URL/)
  assert.match(files.liveSendRehearsalScript, /credentials: 'include'/)
  assert.match(files.packageJson, /"test:e2e:live:rehearsal": "node scripts\/e2e-live-send-rehearsal\.mjs"/)
  assert.match(files.liveSendRehearsalScript, /CLAPCHEEKS_LIVE_SEND_REHEARSAL/)
  assert.match(files.liveSendRehearsalScript, /clapcheeks-live-send-rehearsal\.json/)
  assert.match(files.liveSendRehearsalScript, /sample_757/)
  assert.match(files.liveSendRehearsalScript, /\/api\/scheduled-messages/)
  assert.match(files.liveSendRehearsalScript, /status: 'approved'/)
  assert.match(files.liveSendRehearsalScript, /dry_run: true/)
  assert.match(files.liveSendRehearsalScript, /confirm_send: true/)
  assert.match(files.liveSendRehearsalScript, /osascript Messages\.send/)
  assert.match(files.liveSendRehearsalScript, /message_sha256_match/)
  assert.match(files.liveSendRehearsalScript, /destination_last4_match/)
  assert.match(files.liveSendRehearsalScript, /no_live_send_performed: true/)
  assert.match(files.liveSendRehearsalScript, /no_raw_phone_written/)
  assert.match(files.liveSendRehearsalScript, /no_raw_body_written/)
  assert.match(files.completionAuditScript, /final live-send no-send rehearsal matches redacted preflight plan/)
  assert.match(files.completionAuditScript, /liveSendRehearsalEvidencePath/)
  assert.match(files.readinessStatusScript, /Live-send rehearsal:/)
  assert.match(files.evidenceIndexScript, /live_send_rehearsal/)
  assert.match(files.evidenceIndexScript, /test:e2e:live:rehearsal/)
})

test('runtime smoke verifier proves Convex schema and inbound Messages DB without sends', () => {
  assert.match(files.packageJson, /"test:e2e:runtime": "node scripts\/e2e-runtime-smoke-safe\.mjs"/)
  assert.match(files.runtimeSmokeScript, /clapcheeks\.scripts\.e2e_smoke/)
  assert.match(files.runtimeSmokeScript, /--no-send/)
  assert.match(files.runtimeSmokeScript, /convex/)
  assert.match(files.runtimeSmokeScript, /schema/)
  assert.match(files.runtimeSmokeScript, /inbound/)
  assert.match(files.runtimeSmokeScript, /outbound_insert/)
  assert.match(files.runtimeSmokeScript, /drainer/)
  assert.match(files.runtimeSmokeScript, /outbound_insert_skipped/)
  assert.match(files.runtimeSmokeScript, /drainer_skipped/)
  assert.match(files.runtimeSmokeScript, /inbound_message_rows/)
  assert.match(files.runtimeSmokeScript, /CLAPCHEEKS_INBOUND_WATCHER_STATUS/)
  assert.match(files.runtimeSmokeScript, /CLAPCHEEKS_INBOUND_TERMINAL_PROOF/)
  assert.match(files.runtimeSmokeScript, /inbound_watcher_ok/)
  assert.match(files.runtimeSmokeScript, /inbound_terminal_proof_ok/)
  assert.match(files.runtimeSmokeScript, /fda_alert_imessage_enabled/)
  assert.match(files.runtimeSmokeScript, /no_live_send_performed/)
  assert.match(files.completionAuditScript, /clapcheeks-runtime-smoke-evidence\.json/)
  assert.match(files.completionAuditScript, /clapcheeks-live-send-sample-preflight\.json/)
  assert.match(files.completionAuditScript, /sampleRawPhone/)
  assert.match(files.completionAuditScript, /sampleLivePreflightRawPhoneAbsent/)
  assert.match(files.completionAuditScript, /raw_body_absent/)
  assert.match(files.readinessStatusScript, /Runtime smoke:/)
  assert.match(files.readinessStatusScript, /inbound_watcher_blocker/)
  assert.match(files.readinessStatusScript, /Runtime terminal proof:/)
  assert.match(files.readinessStatusScript, /Inbound repair harness:/)
  assert.match(files.readinessStatusScript, /Inbound repair TCC:/)
  assert.match(files.readinessStatusScript, /tcc_python_authorized/)
  assert.match(files.readinessStatusScript, /tcc_python_denied_or_off/)
  assert.match(files.readinessStatusScript, /CLAPCHEEKS_INBOUND_REPAIR_EVIDENCE/)
  assert.match(files.evidenceIndexScript, /runtime_smoke/)
  assert.match(files.evidenceIndexScript, /runtime_inbound_watcher_blocker/)
  assert.match(files.evidenceIndexScript, /runtime_terminal_proof_ok/)
  assert.match(files.evidenceIndexScript, /inbound_repair/)
  assert.match(files.evidenceIndexScript, /Inbound repair TCC:/)
  assert.match(files.evidenceIndexScript, /inbound_repair_tcc_python_authorized/)
  assert.match(files.evidenceIndexScript, /inbound_repair_tcc_python_denied_or_off/)
  assert.match(files.evidenceIndexScript, /clapcheeks-inbound-watcher-fda-repair-2026-05-18\.json/)
})

test('backend doctor verifies Convex route coverage without sends or mutations', () => {
  assert.match(files.packageJson, /"test:e2e:backend-doctor": "node scripts\/e2e-backend-doctor-safe\.mjs"/)
  assert.match(files.readinessAllScript, /npm run test:e2e:backend-doctor/)
  assert.match(files.backendDoctorScript, /CLAPCHEEKS_BACKEND_DOCTOR_EVIDENCE/)
  assert.match(files.backendDoctorScript, /CLAPCHEEKS_BACKEND_DOCTOR_USE_CCT/)
  assert.match(files.backendDoctorScript, /CLAPCHEEKS_CCT_DEBUG_URL/)
  assert.match(files.backendDoctorScript, /authenticated_cct_fetch/)
  assert.match(files.backendDoctorScript, /credentials: 'include'/)
  assert.match(files.backendDoctorScript, /clapcheeks-backend-doctor-2026-05-18\.json/)
  assert.match(files.backendDoctorScript, /no runtime Supabase imports in dashboard path/)
  assert.match(files.backendDoctorScript, /Convex facade mapping coverage/)
  assert.match(files.backendDoctorScript, /backend API route matrix/)
  assert.match(files.backendDoctorScript, /conversations:listForUser/)
  assert.match(files.backendDoctorScript, /outbound:enqueueScheduledMessage/)
  assert.match(files.backendDoctorScript, /typeof analyticsMatches === 'number'/)
  assert.match(files.backendDoctorScript, /no_live_send_performed: true/)
  assert.match(files.backendDoctorScript, /no_dashboard_mutation_performed: true/)
  assert.match(files.completionAuditScript, /backend Convex and schema route coverage doctor passes/)
  assert.match(files.completionAuditScript, /backendDoctorEvidencePath/)
  assert.match(files.evidenceIndexScript, /backend_doctor/)
  assert.match(files.evidenceIndexScript, /Backend doctor:/)
  assert.match(files.readinessStatusScript, /Backend doctor:/)
  assert.match(files.readinessStatusScript, /backend_doctor/)
})

test('cold-start safe readiness suite owns and cleans up local server lifecycle', () => {
  assert.match(files.packageJson, /"test:e2e:readiness:local": "\.\/scripts\/e2e-readiness-local-safe\.sh"/)
  assert.match(files.readinessLocalScript, /npm run dev:runtime/)
  assert.match(files.readinessLocalScript, /CLAPCHEEKS_SELF_TEST_PHONE/)
  assert.match(files.readinessLocalScript, /npm run test:e2e:readiness/)
  assert.match(files.readinessLocalScript, /trap cleanup EXIT INT TERM/)
  assert.match(files.readinessLocalScript, /kill "\$SERVER_PID"/)
  assert.match(files.readinessLocalScript, /Port \$\{PORT\} is already in use/)
})

test('readiness status reporter summarizes remaining live-send gate without mutation', () => {
  assert.match(files.packageJson, /"test:e2e:status": "node scripts\/e2e-readiness-status\.mjs"/)
  assert.match(files.readinessStatusScript, /ClapCheeks readiness/)
  assert.match(files.readinessStatusScript, /safe_to_continue_without_live_send/)
  assert.match(files.readinessStatusScript, /clapcheeks-safe-e2e-readiness\.json/)
  assert.match(files.readinessStatusScript, /function getSafeCheck/)
  assert.match(files.readinessStatusScript, /scheduled_flow/)
  assert.match(files.readinessStatusScript, /Scheduled flow:/)
  assert.match(files.readinessStatusScript, /Scheduled live gate:/)
  assert.match(files.readinessStatusScript, /Scheduled live gate plan:/)
  assert.match(files.readinessStatusScript, /live_preflight_redacted_plan_present/)
  assert.match(files.readinessStatusScript, /CLAPCHEEKS_LIVE_SEND_APPROVAL_PACKET/)
  assert.match(files.readinessStatusScript, /clapcheeks-live-send-approval-packet-2026-05-18\.json/)
  assert.match(files.readinessStatusScript, /approval_packet/)
  assert.match(files.readinessStatusScript, /Approval packet:/)
  assert.match(files.readinessStatusScript, /raw_phone_written/)
  assert.match(files.readinessStatusScript, /raw_body_written/)
  assert.match(files.readinessStatusScript, /missing_base_env/)
  assert.match(files.readinessStatusScript, /scheduled live blocked by preflight gate/)
  assert.match(files.readinessStatusScript, /live_blocked_by_preflight_gate/)
  assert.match(files.readinessStatusScript, /live_preflight_gate_status/)
  assert.match(files.readinessStatusScript, /scheduled create/)
  assert.match(files.readinessStatusScript, /scheduled approve/)
  assert.match(files.readinessStatusScript, /scheduled dry-run/)
  assert.match(files.readinessStatusScript, /dry_run_provenance_verified/)
  assert.match(files.readinessStatusScript, /dry_run_provenance/)
  assert.match(files.safeReadinessScript, /provenanceOk/)
  assert.match(files.safeReadinessScript, /clapcheeks_scheduled_messages_send_api/)
  assert.match(files.readinessStatusScript, /scheduled fixture cleanup/)
  assert.match(files.readinessStatusScript, /insights_data/)
  assert.match(files.readinessStatusScript, /Insights data:/)
  assert.match(files.readinessStatusScript, /analytics summary contract/)
  assert.match(files.readinessStatusScript, /dashboard_health/)
  assert.match(files.readinessStatusScript, /Dashboard health:/)
  assert.match(files.readinessStatusScript, /blockers=/)
  assert.match(files.readinessStatusScript, /missing_required_services/)
  assert.match(files.readinessStatusScript, /dashboard runtime health contract/)
  assert.match(files.readinessStatusScript, /real outbound send-to-Julian test/)
  assert.match(files.readinessStatusScript, /safe sample 757-831-2944 used without accidental real outbound send/)
  assert.match(files.readinessStatusScript, /Messages DB sample proof/)
  assert.match(files.readinessStatusScript, /sample_outbound_rows/)
  assert.match(files.readinessStatusScript, /content_logged/)
  assert.match(files.readinessStatusScript, /clapcheeks-live-send-preflight\.json/)
  assert.match(files.readinessStatusScript, /clapcheeks-live-send-sample-preflight\.json/)
  assert.match(files.readinessStatusScript, /Live preflight:/)
  assert.match(files.readinessStatusScript, /Live preflight plan:/)
  assert.match(files.readinessStatusScript, /Sample 757 preflight:/)
  assert.match(files.readinessStatusScript, /Sample 757 preflight plan:/)
  assert.match(files.readinessStatusScript, /Sample 757 redaction:/)
  assert.match(files.readinessStatusScript, /raw_phone_absent/)
  assert.match(files.readinessStatusScript, /raw_body_absent/)
  assert.match(files.readinessStatusScript, /message_sha256/)
  assert.match(files.readinessStatusScript, /Final gate:/)
  assert.match(files.readinessStatusScript, /Live\/preflight match:/)
  assert.match(files.readinessStatusScript, /live_evidence_matches_preflight/)
  assert.match(files.readinessStatusScript, /body_hash_match/)
  assert.match(files.readinessStatusScript, /body_length_match/)
  assert.match(files.readinessStatusScript, /destination_last4_match/)
  assert.match(files.readinessStatusScript, /clapcheeks-e2e-evidence-index-2026-05-18\.json/)
  assert.match(files.readinessStatusScript, /visual_evidence/)
  assert.match(files.readinessStatusScript, /Visual evidence:/)
  assert.match(files.readinessStatusScript, /Dashboard navigation:/)
  assert.match(files.readinessStatusScript, /Dashboard blocker quick view:/)
  assert.match(files.readinessStatusScript, /dashboard_health_blockers_quick_view/)
  assert.match(files.readinessStatusScript, /dashboard_navigation_integrity/)
  assert.match(files.readinessStatusScript, /dashboard_navigation/)
  assert.match(files.readinessStatusScript, /Dashboard iMessage self-test:/)
  assert.match(files.readinessStatusScript, /dashboard_imessage_self_test_surface/)
  assert.match(files.readinessStatusScript, /dashboard_imessage_self_test/)
  assert.match(files.readinessStatusScript, /Dashboard iMessage dry-run click:/)
  assert.match(files.readinessStatusScript, /dashboard_imessage_dry_run_click/)
  assert.match(files.readinessStatusScript, /dashboard_imessage_dry_run/)
  assert.match(files.readinessStatusScript, /browser_screenshots_all_present/)
  assert.match(files.readinessStatusScript, /visual_screenshots_all_present/)
  assert.match(files.readinessStatusScript, /visual_screenshots/)
  assert.match(files.readinessStatusScript, /CLAPCHEEKS_DEVICE_BLOCKER_CCT_LATEST/)
  assert.match(files.readinessStatusScript, /deviceControlStatusFromProductionCct/)
  assert.match(files.readinessStatusScript, /production_cct_device_status/)
  assert.match(files.readinessStatusScript, /on_device_developer_mode_confirmation/)
  assert.match(files.readinessStatusScript, /Developer Mode menu was revealed/)
  assert.match(files.readinessStatusScript, /deviceBlockerCct/)
  assert.match(files.readinessStatusScript, /latest_blockers_source/)
  assert.match(files.readinessStatusScript, /transport_telemetry_event_id/)
  assert.match(files.readinessStatusScript, /mobile_metric_count/)
  assert.match(files.readinessStatusScript, /mobile_metrics_overflow_free/)
  assert.match(files.readinessStatusScript, /Mobile metrics:/)
  assert.match(files.readinessStatusScript, /Scheduled mobile form:/)
  assert.match(files.readinessStatusScript, /scheduled_mobile_form_filled/)
  assert.match(files.readinessStatusScript, /scheduled_ui_matches_api/)
  assert.match(files.readinessStatusScript, /Scheduled UI\/API/)
  assert.match(files.readinessStatusScript, /scheduled_mobile_form_no_submit/)
  assert.match(files.readinessStatusScript, /Scheduled send confirmation:/)
  assert.match(files.readinessStatusScript, /scheduled_send_confirmation_guardrail/)
  assert.match(files.readinessStatusScript, /send_disabled_with_wrong_phrase/)
  assert.match(files.readinessStatusScript, /Intelligence UI\/API:/)
  assert.match(files.readinessStatusScript, /intelligence_ui_matches_api/)
  assert.match(files.readinessStatusScript, /intelligence_api_binding/)
  assert.match(files.readinessStatusScript, /Analytics mobile UI\/API:/)
  assert.match(files.readinessStatusScript, /analytics_mobile_ui_matches_api/)
  assert.match(files.readinessStatusScript, /analytics_mobile_api_binding/)
  assert.match(files.readinessStatusScript, /Artifact freshness:/)
  assert.match(files.readinessStatusScript, /current_production_fresh/)
  assert.match(files.readinessStatusScript, /historical_fresh/)
  assert.match(files.readinessStatusScript, /artifact_freshness/)
  assert.match(files.readinessStatusScript, /function ageSeconds/)
  assert.match(files.readinessStatusScript, /evidence_index_age_seconds/)
  assert.match(files.readinessStatusScript, /evidence_index_generated_at/)
  assert.match(files.readinessStatusScript, /artifacts: evidenceIndex\?\.artifacts/)
  assert.match(files.readinessStatusScript, /live_harness_missing_base_env/)
  assert.match(files.readinessStatusScript, /evidence_mismatch/)
  assert.match(files.readinessStatusScript, /no_dashboard_mutation_performed/)
  assert.match(files.readinessStatusScript, /function nextRequiredAction/)
  assert.match(files.readinessStatusScript, /Repair missing non-live evidence first/)
  assert.match(files.readinessStatusScript, /runtime inbound source of truth is reachable in no-send mode/)
  assert.match(files.readinessStatusScript, /scripts\/repair-inbound-watcher-fda\.sh/)
  assert.match(files.readinessStatusScript, /full_disk_access_missing/)
  assert.match(files.readinessStatusScript, /CLAPCHEEKS_LIVE_SEND_ALLOW_SAMPLE_2944/)
  assert.match(files.readinessStatusScript, /Confirm whether 757-831-2944 is intentionally the live destination/)
  assert.match(files.readinessStatusScript, /docs\/e2e-live-send-runbook\.md/)
  assert.match(files.readinessStatusScript, /Get Julian-confirmed destination phone/)
  assert.doesNotMatch(files.readinessStatusScript, /fetch\(/)
})

test('evidence index consolidates readiness artifacts and repeatable commands', () => {
  assert.match(files.packageJson, /"test:e2e:evidence": "node scripts\/e2e-evidence-index\.mjs"/)
  assert.match(files.evidenceIndexScript, /clapcheeks-safe-e2e-readiness\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-browser-visual-evidence-2026-05-18\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-runtime-smoke-evidence\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-inbound-watcher-fda-repair-2026-05-18\.json/)
  assert.match(files.evidenceIndexScript, /Inbound repair harness:/)
  assert.match(files.evidenceIndexScript, /clapcheeks-local-browser-proof-2026-05-18\.json/)
  assert.match(files.evidenceIndexScript, /'local_browser'/)
  assert.match(files.evidenceIndexScript, /clapcheeks-live-send-evidence\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-live-send-preflight\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-live-send-sample-preflight\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-live-send-approval-packet-2026-05-18\.json/)
  assert.match(files.evidenceIndexScript, /clapcheeks-live-send-approval-packet-2026-05-18\.md/)
  assert.match(files.evidenceIndexScript, /'approval_packet'/)
  assert.match(files.evidenceIndexScript, /'approval_packet_markdown'/)
  assert.match(files.evidenceIndexScript, /clapcheeks-prod-device-blocker-cct-latest\.json/)
  assert.match(files.evidenceIndexScript, /'device_blocker_cct'/)
  assert.match(files.evidenceIndexScript, /productionDeviceStatus/)
  assert.match(files.evidenceIndexScript, /production_cct_device_status/)
  assert.match(files.evidenceIndexScript, /productionDeviceStatus \? \[\] : \['device_blocker_cct'\]/)
  assert.match(files.evidenceIndexScript, /device_control_latest_blockers_source/)
  assert.match(files.evidenceIndexScript, /device_control_transport_event_id/)
  assert.match(files.evidenceIndexScript, /clapcheeks-completion-audit-2026-05-18\.json/)
  assert.match(files.evidenceIndexScript, /sample_live_preflight_ready/)
  assert.match(files.evidenceIndexScript, /sample_live_preflight_raw_phone_absent/)
  assert.match(files.evidenceIndexScript, /raw_body_absent/)
  assert.match(files.evidenceIndexScript, /Sample 757 preflight:/)
  assert.match(files.evidenceIndexScript, /test:e2e:readiness:local/)
  assert.match(files.evidenceIndexScript, /test:e2e:local-browser/)
  assert.match(files.evidenceIndexScript, /test:e2e:live:approval-packet/)
  assert.match(files.evidenceIndexScript, /test:e2e:live:sample-preflight/)
  assert.match(files.evidenceIndexScript, /final_gate_command_reference/)
  assert.match(files.evidenceIndexScript, /final_gate_next_required_action/)
  assert.match(files.evidenceIndexScript, /evidence_highlights\.final_gate/)
  assert.match(files.evidenceIndexScript, /no_live_send_performed/)
  assert.match(files.evidenceIndexScript, /dashboard_navigation_integrity/)
  assert.match(files.evidenceIndexScript, /dashboard_health_blockers_quick_view/)
  assert.match(files.evidenceIndexScript, /dashboard_health_blockers_expected/)
  assert.match(files.evidenceIndexScript, /dashboard_imessage_self_test_surface/)
  assert.match(files.evidenceIndexScript, /dashboard_imessage_dry_run_click/)
  assert.match(files.evidenceIndexScript, /dashboard_imessage_dry_run_no_queue_delta/)
  assert.match(files.evidenceIndexScript, /browser_screenshot_count/)
  assert.match(files.evidenceIndexScript, /browser_screenshots_all_present/)
  assert.match(files.evidenceIndexScript, /production_cct_screenshot_count/)
  assert.match(files.evidenceIndexScript, /production_cct_screenshots_all_present/)
  assert.match(files.evidenceIndexScript, /visual_screenshot_count/)
  assert.match(files.evidenceIndexScript, /visual_screenshots_all_present/)
  assert.match(files.evidenceIndexScript, /scheduled_dry_run_provenance_verified/)
  assert.match(files.evidenceIndexScript, /scheduled_dry_run/)
  assert.match(files.evidenceIndexScript, /CLAPCHEEKS_EVIDENCE_MAX_AGE_SECONDS/)
  assert.match(files.evidenceIndexScript, /artifact_freshness/)
  assert.match(files.evidenceIndexScript, /currentProductionFreshArtifactKeys/)
  assert.match(files.evidenceIndexScript, /current_production_artifacts_fresh/)
  assert.match(files.evidenceIndexScript, /historical_artifacts_fresh/)
  assert.match(files.evidenceIndexScript, /stale_artifacts/)
  assert.match(files.evidenceIndexScript, /browser_screenshots/)
  assert.match(files.evidenceIndexScript, /production_cct_screenshots/)
  assert.match(files.evidenceIndexScript, /visual_screenshots/)
  assert.match(files.evidenceIndexScript, /Browser screenshots:/)
  assert.match(files.evidenceIndexScript, /mobile_metric_count/)
  assert.match(files.evidenceIndexScript, /mobile_metrics_overflow_free/)
  assert.match(files.evidenceIndexScript, /scheduled_mobile_form_filled/)
  assert.match(files.evidenceIndexScript, /scheduled_ui_matches_api/)
  assert.match(files.evidenceIndexScript, /scheduled_api_counts_match/)
  assert.match(files.evidenceIndexScript, /scheduled_mobile_form_no_submit/)
  assert.match(files.evidenceIndexScript, /scheduled_send_confirmation_guardrail/)
  assert.match(files.evidenceIndexScript, /scheduled_send_confirmation_cleanup/)
  assert.match(files.evidenceIndexScript, /scheduled_live_blocked_by_preflight_gate/)
  assert.match(files.evidenceIndexScript, /scheduled_live_preflight_no_send/)
  assert.match(files.evidenceIndexScript, /scheduled_live_preflight_gate/)
  assert.match(files.evidenceIndexScript, /Scheduled live gate:/)
  assert.match(files.evidenceIndexScript, /intelligence_ui_matches_api/)
  assert.match(files.evidenceIndexScript, /analytics_mobile_ui_matches_api/)
  assert.match(files.evidenceIndexScript, /analytics_mobile_quick_view/)
  assert.match(files.evidenceIndexScript, /Mobile metrics:/)
  assert.match(files.evidenceIndexScript, /messages_db_sample_rows/)
  assert.match(files.evidenceIndexScript, /Messages DB sample proof/)
  assert.match(files.evidenceIndexScript, /sample_outbound_rows/)
  assert.match(files.evidenceIndexScript, /content_logged/)
  assert.match(files.evidenceIndexScript, /live_preflight/)
  assert.match(files.evidenceIndexScript, /Live preflight:/)
  assert.match(files.evidenceIndexScript, /local_browser_proof_ok/)
  assert.match(files.evidenceIndexScript, /Local Chrome proof:/)
  assert.match(files.evidenceIndexScript, /approval_packet_ready/)
  assert.match(files.evidenceIndexScript, /Approval packet:/)
  assert.match(files.evidenceIndexScript, /raw_phone_written/)
  assert.match(files.evidenceIndexScript, /markdown_e164_absent/)
  assert.match(files.evidenceIndexScript, /markdown_body_absent/)
  assert.match(files.evidenceIndexScript, /forbidden_fixture_present/)
  assert.match(files.evidenceIndexScript, /Final gate blockers/)
  assert.match(files.evidenceIndexScript, /Next required action:/)
  assert.match(files.evidenceIndexScript, /Live\/preflight match:/)
  assert.match(files.evidenceIndexScript, /live_evidence_matches_preflight/)
  assert.match(files.evidenceIndexScript, /live_body_hash_match/)
  assert.match(files.evidenceIndexScript, /live_body_length_match/)
  assert.match(files.evidenceIndexScript, /live_destination_last4_match/)
  assert.match(files.evidenceIndexScript, /live_harness_missing_base_env/)
  assert.match(files.evidenceIndexScript, /final_gate_evidence_mismatch/)
  assert.match(files.evidenceIndexScript, /no_dashboard_mutation_performed/)
})

test('local Chrome proof reads the real browser tab and only performs read-only checks', () => {
  assert.match(files.packageJson, /"test:e2e:local-browser": "node scripts\/e2e-local-browser-proof\.mjs"/)
  assert.match(files.localBrowserProofScript, /CLAPCHEEKS_LOCAL_BROWSER_USE_CCT/)
  assert.match(files.localBrowserProofScript, /CCT tab did not expose a debugger URL/)
  assert.match(files.localBrowserProofScript, /credentials: 'include'/)
  assert.match(files.localBrowserProofScript, /Google Chrome/)
  assert.match(files.localBrowserProofScript, /openChromeLocalRoute/)
  assert.match(files.localBrowserProofScript, /set URL of active tab of front window/)
  assert.match(files.localBrowserProofScript, /osascript/)
  assert.match(files.localBrowserProofScript, /CLAPCHEEKS_LOCAL_BROWSER_PROOF/)
  assert.match(files.localBrowserProofScript, /clapcheeks-local-browser-proof-2026-05-18\.json/)
  assert.match(files.localBrowserProofScript, /api\/scheduled-messages\?status=all&limit=100/)
  assert.match(files.localBrowserProofScript, /api\/analytics\/summary\?days=30/)
  assert.match(files.localBrowserProofScript, /no_live_send_performed: true/)
  assert.match(files.localBrowserProofScript, /no_dashboard_mutation_performed: true/)
  assert.match(files.localBrowserProofScript, /Safe Browser Proof 2944/)
  assert.match(files.localBrowserProofScript, /Safe browser proof only\. Do not send\./)
  assert.match(files.localBrowserProofScript, /forbidden_fixture_present/)
  assert.match(files.localBrowserProofScript, /analytics_matches_numeric/)
  assert.match(files.completionAuditScript, /localBrowser\.analytics\.summary\.matches >= 0/)
  assert.match(files.completionAuditScript, /browser\.checks\.analytics_summary\.matches >= 0/)
  assert.doesNotMatch(files.localBrowserProofScript, /fetch\([^)]*,\\s*\\{[^}]*method: ['"]POST/)
})

test('browser visual proof records durable mobile viewport metrics', () => {
  assert.match(files.browserVisualScript, /capture_metrics/)
  assert.match(files.browserVisualScript, /mobile_metric_js/)
  assert.match(files.browserVisualScript, /inner_width/)
  assert.match(files.browserVisualScript, /scroll_width/)
  assert.match(files.browserVisualScript, /overflow_x/)
  assert.match(files.browserVisualScript, /dashboard-mobile-metrics\.json/)
  assert.match(files.browserVisualScript, /scheduled-mobile-metrics\.json/)
  assert.match(files.browserVisualScript, /scheduled-mobile-modal-metrics\.json/)
  assert.match(files.browserVisualScript, /scheduled_send_confirmation_modal/)
  assert.match(files.browserVisualScript, /intelligence-mobile-metrics\.json/)
  assert.match(files.browserVisualScript, /analytics-mobile-metrics\.json/)
  assert.match(files.browserVisualScript, /mobile_metrics_overflow_free/)
  assert.match(files.completionAuditScript, /mobile_metrics_overflow_free/)
  assert.match(files.completionAuditScript, /mobile_metrics/)
  assert.match(files.completionAuditScript, /dashboard_health_blockers_quick_view/)
})

test('production CCT proof covers dashboard health, roster controls, and current transport blockers', () => {
  assert.match(files.productionCctScript, /operatorPassword\(\)/)
  assert.match(files.productionCctScript, /find-generic-password/)
  assert.match(files.productionCctScript, /ensureAuthenticated/)
  assert.match(files.productionCctScript, /source: 'operator_login'/)
  assert.match(files.productionCctScript, /dashboard health card renders live service status/)
  assert.match(files.productionCctScript, /roster search and filter controls render/)
  assert.match(files.productionCctScript, /settings report controls render/)
  assert.match(files.productionCctScript, /AI settings voice and approval controls render/)
  assert.match(files.productionCctScript, /leads stage board renders funnel controls/)
  assert.match(files.productionCctScript, /lead edit persists through match patch API/)
  assert.match(files.productionCctScript, /lead_stage: 'date_booked'/)
  assert.match(files.productionCctScript, /lead_outcome: 'production_cct_verified'/)
  assert.match(files.productionCctScript, /sanitizedFixtureEvidence/)
  assert.match(files.productionCctScript, /lead_tag_present/)
  assert.match(files.productionCctScript, /lead_notes_present/)
  assert.match(files.productionCctScript, /key === 'scheduled'/)
  assert.match(files.productionCctScript, /redacted: true/)
  assert.match(files.productionCctScript, /\/api\/match-profile\/enrich/)
  assert.match(files.productionCctScript, /fixture\.enrichStatus === 200/)
  assert.match(files.productionCctScript, /fixture\.leadEditStatus === 200/)
  assert.match(files.productionCctScript, /Refresh health check/)
  assert.match(files.productionCctScript, /Search roster/)
  assert.match(files.productionCctScript, /Favorites/)
  assert.match(files.productionCctScript, /At-risk health/)
  assert.match(files.productionCctScript, /Save preferences/)
  assert.match(files.productionCctScript, /Approval gates/)
  assert.match(files.productionCctScript, /Date proposed/)
  assert.match(files.productionCctScript, /device status uses latest transport telemetry source/)
  assert.match(files.productionCctScript, /latest_completion_audit_telemetry/)
  assert.match(files.productionCctScript, /physical\.telemetry_event_id/)
  assert.match(files.productionCctScript, /physical\.telemetry_occurred_at/)
  assert.match(files.productionCctScript, /deviceStatus: deviceSummary/)
  assert.match(files.productionCctScript, /transportBlockers\.every/)
  assert.doesNotMatch(files.productionCctScript, /ios_deploy_bound_udid_visible === true/)
})
