import { test } from 'node:test'
import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'

const files = {
  status: readFileSync('app/api/device-control/status/route.ts', 'utf8'),
  observe: readFileSync('app/api/device-control/observe/route.ts', 'utf8'),
  action: readFileSync('app/api/device-control/action/route.ts', 'utf8'),
  proof: readFileSync('app/api/device-control/proof/route.ts', 'utf8'),
  proofAll: readFileSync('app/api/device-control/proof-all/route.ts', 'utf8'),
  jobStatus: readFileSync('app/api/device-control/jobs/[id]/route.ts', 'utf8'),
  devicePage: readFileSync('app/(main)/device/page.tsx', 'utf8'),
  devicePanel: readFileSync('app/(main)/device/device-control-panel.tsx', 'utf8'),
}

test('device-control observe and action routes advertise and accept only known adapters', () => {
  for (const source of [files.status, files.observe, files.action]) {
    assert.match(source, /observe-only/)
    assert.match(source, /macos-screen/)
    assert.match(source, /physical-ios/)
  }
  assert.match(files.observe, /adapter must be observe-only, macos-screen, or physical-ios/)
  assert.match(files.action, /adapter must be observe-only, macos-screen, or physical-ios/)
})

test('status route names the current physical-ios readiness blocker', () => {
  assert.match(files.status, /observe_only_until_physical_iphone_screenshot_verified/)
  assert.match(files.status, /selected_udid: '00008150-00093C9C3C7A401C'/)
  assert.match(files.status, /currentPhysicalIOSBlocker/)
  assert.match(files.status, /latest_known_blockers: physicalIOSBlockers/)
  assert.match(files.status, /latest_blockers_source/)
  assert.match(files.status, /latest_completion_audit_json/)
  assert.match(files.status, /no_physical_ios_device_visible/)
  assert.match(files.status, /developer_mode_disabled_on_physical_iphone/)
  assert.match(files.status, /physical_ios_device_not_visible_to_xcode/)
  assert.match(files.status, /usbmux_no_bound_udid/)
  assert.match(files.status, /ios_deploy_no_bound_udid/)
  assert.match(files.status, /pairing_record_missing_for_bound_udid/)
  assert.match(files.status, /coredevice_no_bound_udid/)
  assert.match(files.status, /physical_ios_observe_png_not_verified/)
  assert.match(files.status, /proof_runner/)
  assert.match(files.status, /prepare-device-control-readiness\.sh/)
  assert.match(files.status, /run-device-control-transport-diagnostics\.sh/)
  assert.match(files.status, /prepare-device-control-developer-mode\.sh/)
  assert.match(files.status, /prepare-device-control-coredevice\.sh/)
  assert.match(files.status, /run-device-control-physical-proof\.sh/)
  assert.match(files.status, /run-device-control-all-platform-proofs\.sh/)
  assert.match(files.status, /watch-device-control-physical-proof\.sh/)
  assert.match(files.status, /run-device-control-completion-audit\.sh/)
  assert.match(files.status, /getRuntimeHealth/)
  assert.match(files.status, /getInboundWatcherHealth/)
  assert.match(files.status, /inbound_watcher/)
  assert.match(files.status, /telemetry_event_id/)
  assert.match(files.status, /telemetry_age_ms/)
  assert.match(files.status, /open-inbound-watcher-fda-settings\.sh/)
  assert.match(files.status, /repair-inbound-watcher-fda\.sh/)
  assert.match(files.status, /tech\.clapcheeks\.inbound-watcher/)
  assert.match(files.status, /required_python_app/)
  assert.match(files.status, /repair_verify_command/)
  assert.match(files.status, /terminal_read_proof/)
  assert.match(files.status, /readInboundRepairTcc/)
  assert.match(files.status, /full_disk_access_tcc/)
  assert.match(files.status, /python_authorized/)
  assert.match(files.status, /python_denied_or_off/)
  assert.match(files.status, /auth_value/)
  assert.match(files.status, /npm run test:e2e:runtime/)
  assert.match(files.status, /readiness_command/)
  assert.match(files.status, /transport_diagnostics_command/)
  assert.match(files.status, /prepare_developer_mode_command/)
  assert.match(files.status, /prepare_coredevice_command/)
  assert.match(files.status, /all_platforms_command/)
  assert.match(files.status, /watch_command/)
	  assert.match(files.status, /completion_audit_command/)
	  assert.match(files.status, /proof_run_dir/)
	  assert.match(files.status, /completion_audit/)
	  assert.match(files.status, /success_criteria/)
	  assert.match(files.status, /artifact_checklist/)
	  assert.match(files.status, /latest_result_path/)
	  assert.match(files.status, /latest_result/)
	  assert.match(files.status, /readLatestCompletionAudit/)
	  assert.match(files.status, /failed_checks/)
	  assert.match(files.status, /blockers/)
	  assert.match(files.status, /next_unblock_steps/)
	  assert.match(files.status, /readiness_command/)
  assert.match(files.status, /parsed\.transport_diagnostics_command/)
  assert.match(files.status, /transport_visibility/)
  assert.match(files.status, /cleanObject/)
  assert.match(files.status, /latest-completion-audit\.json/)
	  assert.match(files.status, /strict doctor, wait-proof, and one physical PNG proof must pass before completion/)
	  assert.match(files.status, /secondary_number_iphone/)
	  assert.match(files.status, /transport_diagnostics/)
	  assert.match(files.status, /completion_decision/)
  assert.match(files.status, /const localLatestCompletionAudit = readLatestCompletionAudit\(\)/)
  assert.match(files.status, /const latestCompletionAudit = await latestCompletionAuditForUser\(user\.id\)/)
  assert.match(files.status, /latestCompletionAuditForUser/)
  assert.match(files.status, /readLatestCompletionAuditFromTelemetry/)
  assert.match(files.status, /device_control\.completion_audit/)
  assert.match(files.status, /const physicalIOSBlockers = latestPhysicalIOSBlockers\(latestCompletionAudit\)/)
  assert.match(files.status, /\.\.\.physicalIOSBlockers/)
  assert.match(files.status, /transport_visibility: latestCompletionAudit\.transport_visibility/)
  assert.match(files.status, /latest_result: latestCompletionAudit/)
  assert.match(files.status, /sendbird: tokenHealth\.sendbird/)
  assert.match(files.devicePanel, /Hinge proxy capture/)
  assert.match(files.devicePanel, /proxy_listening/)
  assert.match(files.devicePanel, /missing_fields/)
  assert.match(files.devicePanel, /Open Hinge chat through the proxied device/)
  assert.match(files.devicePage, /sendBirdCapture/)
  assert.match(files.devicePage, /Last snapshot/)
})

test('status route derives physical blockers from latest completion audit before fallback', () => {
  assert.match(files.status, /FALLBACK_PHYSICAL_IOS_BLOCKERS/)
  assert.match(files.status, /function latestPhysicalIOSBlockers/)
  assert.match(files.status, /Array\.isArray\(latestAudit\.blockers\) && latestAudit\.blockers\.length > 0/)
  assert.match(files.status, /return latestAudit\.blockers/)
  assert.match(files.status, /return FALLBACK_PHYSICAL_IOS_BLOCKERS/)
  assert.match(files.status, /function currentPhysicalIOSBlocker/)
  assert.match(files.status, /latestAudit\.status === 'passed'/)
  assert.match(files.status, /latest_blockers_source: latestCompletionAudit\.source === 'convex_telemetry'/)
  assert.match(files.status, /latestCompletionAudit\.status === 'missing' \|\| latestCompletionAudit\.status === 'unreadable'/)
  assert.match(files.status, /convex_telemetry/)
})

test('status route exposes the disabled-by-default physical iOS live action env gate', () => {
  assert.match(files.status, /PHYSICAL_IOS_LIVE_ACTION_ENV/)
  assert.match(files.status, /CLAPCHEEKS_PHYSICAL_IOS_ENABLE_LIVE_ACTIONS/)
  assert.match(files.status, /readPhysicalIOSLiveActionGate/)
  assert.match(files.status, /physical_ios_live_actions_enabled/)
  assert.match(files.status, /process\.env\[PHYSICAL_IOS_LIVE_ACTION_ENV\] === '1'/)
  assert.match(files.status, /required_value: '1'/)
  assert.match(files.status, /default_state: 'disabled'/)
  assert.match(files.status, /action_surface: 'physical_ios_appium_xcuitest'/)
  assert.match(files.status, /live_action_gate: readPhysicalIOSLiveActionGate\(\)/)
})

test('action route verifies live approvals against Convex before enqueue', () => {
  assert.match(files.action, /convexMutation, convexQuery/)
  assert.match(files.action, /type ApprovalRecord/)
  assert.match(files.action, /function approvalDecidedAtSeconds/)
  assert.match(files.action, /async function verifyApprovalRecord/)
  assert.match(files.action, /queues:listApprovalsForUser/)
  assert.match(files.action, /verifyApprovalRecord\(user\.id, approvalId\)/)
  assert.match(files.action, /live device actions require Convex approval verification/)
  assert.match(files.action, /!approvalRecord \|\| approvalRecord\.status !== 'approved'/)
  assert.match(files.action, /approvalDecidedAt = approvalDecidedAtSeconds\(approvalRecord\.decided_at\)/)
})

test('action route blocks physical-ios live enqueue unless env gate is enabled', () => {
  assert.match(files.action, /PHYSICAL_IOS_LIVE_ACTION_ENV/)
  assert.match(files.action, /CLAPCHEEKS_PHYSICAL_IOS_ENABLE_LIVE_ACTIONS/)
  assert.match(files.action, /function physicalIOSLiveActionsEnabled/)
  assert.match(files.action, /process\.env\[PHYSICAL_IOS_LIVE_ACTION_ENV\] === '1'/)
  assert.match(files.action, /adapter === 'physical-ios' && !physicalIOSLiveActionsEnabled\(\)/)
  assert.match(files.action, /physical-ios live actions require CLAPCHEEKS_PHYSICAL_IOS_ENABLE_LIVE_ACTIONS=1/)
})

test('action route keeps live sends behind fresh approval and second confirmation', () => {
  assert.match(files.action, /APPROVAL_MAX_AGE_SECONDS = 15 \* 60/)
  assert.match(files.action, /live device actions require approved approval_id/)
  assert.match(files.action, /live device actions require approval_decided_at/)
  assert.match(files.action, /live device action approval is expired/)
  assert.match(files.action, /approval_decided_at: approvalDecidedAt/)
  assert.match(files.action, /live device actions require confirm_live_action=true/)
  assert.match(files.action, /live device actions require confirm_physical_png_proof=true/)
  assert.match(files.action, /live device actions require a fresh physical PNG proof under the device-control screenshot directory/)
  assert.match(files.action, /physical_png_proof_path: physicalPngProofPath/)
  assert.match(files.action, /confirm_physical_png_proof: confirmPhysicalPngProof/)
  assert.match(files.action, /live sends require confirm_outbound_send=true/)
})

test('action route validates physical PNG proof freshness and artifact containment before enqueue', () => {
  assert.match(files.action, /PHYSICAL_PNG_PROOF_MAX_AGE_SECONDS/)
  assert.match(files.action, /CLAPCHEEKS_PHYSICAL_PNG_PROOF_MAX_AGE_SECONDS/)
  assert.match(files.action, /CLAPCHEEKS_DEVICE_CONTROL_ARTIFACT_DIR/)
  assert.match(files.action, /CLAPCHEEKS_RUNTIME_DIR/)
  assert.match(files.action, /deviceControlScreenshotDir/)
  assert.match(files.action, /validatePhysicalPngProofPath/)
  assert.match(files.action, /realpathSync/)
  assert.match(files.action, /statSync/)
  assert.match(files.action, /physical_png_proof_path_required/)
  assert.match(files.action, /physical_png_proof_path_invalid/)
  assert.match(files.action, /physical_png_proof_path_outside_artifact_dir/)
  assert.match(files.action, /physical_png_proof_stale/)
  assert.match(files.action, /const physicalPngProofDenial = validatePhysicalPngProofPath\(physicalPngProofPath\)/)
  assert.match(files.action, /reason: physicalPngProofDenial/)
})

test('action route redacts communication payloads in API responses', () => {
  assert.match(files.action, /safePayloadForResponse/)
  assert.match(files.action, /\['message', 'text', 'body'\]/)
  assert.match(files.action, /\[redacted\]/)
  assert.match(files.action, /`\$\{key\}_length`/)
  assert.match(files.action, /payload: safePayloadForResponse\(payload\)/)
})

test('action route requires object action payloads before enqueue', () => {
  assert.match(files.action, /function cleanActionPayload/)
  assert.match(files.action, /Array\.isArray\(value\)/)
  assert.match(files.action, /action_payload must be an object/)
  assert.match(files.action, /const actionPayload = cleanActionPayload\(body\.action_payload\)/)
  assert.match(files.action, /action_payload: actionPayload/)
})

test('action route validates live action payload shape before enqueue', () => {
  assert.match(files.action, /function validateLiveActionPayload/)
  assert.match(files.action, /function hasPoint/)
  assert.match(files.action, /function hasText/)
  assert.match(files.action, /tap_coordinates_required/)
  assert.match(files.action, /start_x/)
  assert.match(files.action, /start_y/)
  assert.match(files.action, /end_x/)
  assert.match(files.action, /end_y/)
  assert.match(files.action, /duration_ms_coordinate_required/)
  assert.match(files.action, /text_required/)
  assert.match(files.action, /send_button_coordinates_required/)
  assert.match(files.action, /const liveActionPayloadDenial = validateLiveActionPayload\(actionKind, actionPayload\)/)
  assert.match(files.action, /live device actions require action_payload matching the requested action kind/)
  assert.match(files.action, /reason: liveActionPayloadDenial/)
})


test('proof route forces physical-ios screenshot proof semantics', () => {
  assert.match(files.proof, /adapter: 'physical-ios'/)
  assert.match(files.proof, /capture_screenshot: true/)
  assert.match(files.proof, /require_physical_png: true/)
  assert.match(files.proof, /source: 'dashboard_device_control_proof'/)
  assert.match(files.proof, /priority: 3/)
})

test('proof-all route enqueues physical PNG proof for every dating platform', () => {
  assert.match(files.proofAll, /PLATFORMS = \['hinge', 'tinder', 'bumble'\]/)
  assert.match(files.proofAll, /adapter: 'physical-ios'/)
  assert.match(files.proofAll, /require_physical_png: true/)
  assert.match(files.proofAll, /source: 'dashboard_device_control_proof_all'/)
  assert.match(files.proofAll, /agent_jobs:enqueue/)
  assert.match(files.proofAll, /job_ids/)
})


test('device-control routes reject personal line 1 before enqueue', () => {
  for (const source of [files.observe, files.proof, files.proofAll, files.action]) {
    assert.match(source, /line must be a secondary line number >= 2/)
    assert.match(source, /Number\.isInteger\(line\) && line >= 2/)
  }
})

test('status route exposes the runtime line-2 physical-ios binding', () => {
  assert.match(files.status, /selected_line: 2/)
  assert.match(files.status, /selected_phone: '\+16199919355'/)
  assert.match(files.status, /selected_udid: '00008150-00093C9C3C7A401C'/)
  assert.match(files.status, /device_topology/)
  assert.match(files.status, /sender_device: 'secondary_iPhone'/)
  assert.match(files.status, /operator_device: 'iPad_or_dashboard_browser'/)
  assert.match(files.status, /Use the secondary iPhone with the other number/)
})


test('device page renders observe-only physical proof controls without live actions', () => {
  assert.match(files.devicePage, /<DeviceControlPanel \/>/)
  assert.match(files.devicePanel, /\/api\/device-control\/status/)
  assert.match(files.devicePanel, /\/api\/device-control\/\$\{kind\}/)
  assert.match(files.devicePanel, /Queue observe/)
  assert.match(files.devicePanel, /Queue PNG proof/)
  assert.match(files.devicePanel, /Queue all-platform proof/)
  assert.match(files.devicePanel, /Physical PNG proof must pass before any live tap, swipe, type, or send control is exposed here\./)
  assert.match(files.devicePanel, /Post-unlock proof runner/)
  assert.match(files.devicePanel, /Physical readiness blockers/)
  assert.match(files.devicePanel, /latest_known_blockers/)
  assert.match(files.devicePanel, /latest_blockers_source/)
  assert.match(files.devicePanel, /Blockers:/)
  assert.match(files.devicePanel, /latest audit JSON/)
  assert.match(files.devicePanel, /Convex telemetry/)
  assert.match(files.devicePanel, /fallback readiness map/)
  assert.match(files.devicePanel, /readinessBlockers/)
  assert.match(files.devicePanel, /prepare-device-control-readiness\.sh/)
  assert.match(files.devicePanel, /run-device-control-transport-diagnostics\.sh/)
  assert.match(files.devicePanel, /prepare-device-control-developer-mode\.sh/)
  assert.match(files.devicePanel, /prepare-device-control-coredevice\.sh/)
  assert.match(files.devicePanel, /run-device-control-physical-proof\.sh/)
  assert.match(files.devicePanel, /run-device-control-all-platform-proofs\.sh/)
  assert.match(files.devicePanel, /watch-device-control-physical-proof\.sh/)
  assert.match(files.devicePanel, /run-device-control-completion-audit\.sh/)
  assert.match(files.devicePanel, /Inbound watcher unblock/)
  assert.match(files.devicePanel, /inbound_watcher/)
  assert.match(files.devicePanel, /Terminal proof:/)
  assert.match(files.devicePanel, /TCC python:/)
  assert.match(files.devicePanel, /TCC rows:/)
  assert.match(files.devicePanel, /Full Disk Access TCC:/)
  assert.match(files.devicePanel, /python_authorized/)
  assert.match(files.devicePanel, /python_denied_or_off/)
  assert.match(files.devicePanel, /open-inbound-watcher-fda-settings\.sh/)
  assert.match(files.devicePanel, /repair-inbound-watcher-fda\.sh/)
  assert.match(files.devicePanel, /tech\.clapcheeks\.inbound-watcher/)
  assert.match(files.devicePanel, /npm run test:e2e:runtime/)
  assert.match(files.devicePanel, /repair_verify_command/)
  assert.match(files.devicePanel, /readiness_command/)
  assert.match(files.devicePanel, /transport_diagnostics_command/)
  assert.match(files.devicePanel, /prepare_developer_mode_command/)
  assert.match(files.devicePanel, /prepare_coredevice_command/)
  assert.match(files.devicePanel, /all_platforms_command/)
  assert.match(files.devicePanel, /watch_command/)
	  assert.match(files.devicePanel, /completion_audit_command/)
	  assert.match(files.devicePanel, /proof_run_dir/)
	  assert.match(files.devicePanel, /Completion audit checklist/)
	  assert.match(files.devicePanel, /completion_audit/)
	  assert.match(files.devicePanel, /success_criteria/)
	  assert.match(files.devicePanel, /artifact_checklist/)
	  assert.match(files.devicePanel, /latest_result_path/)
	  assert.match(files.devicePanel, /Latest audit result:/)
	  assert.match(files.devicePanel, /latest_result/)
	  assert.match(files.devicePanel, /Failed gates:/)
	  assert.match(files.devicePanel, /failed_checks/)
	  assert.match(files.devicePanel, /blockers/)
	  assert.match(files.devicePanel, /Next physical unblock/)
	  assert.match(files.devicePanel, /next_unblock_steps/)
	  assert.match(files.devicePanel, /readiness_command/)
  assert.match(files.devicePanel, /latest_result\.transport_diagnostics_command/)
  assert.match(files.devicePanel, /Transport visibility/)
  assert.match(files.devicePanel, /transportVisibility/)
  assert.match(files.devicePanel, /usbmux:/)
  assert.match(files.devicePanel, /ios-deploy:/)
  assert.match(files.devicePanel, /Pairing record:/)
  assert.match(files.devicePanel, /CoreDevice:/)
  assert.match(files.devicePanel, /latest-completion-audit\.json/)
  assert.match(files.devicePanel, /live_action_gate/)
  assert.match(files.devicePanel, /Live action env gate/)
  assert.match(files.devicePanel, /CLAPCHEEKS_PHYSICAL_IOS_ENABLE_LIVE_ACTIONS/)
  assert.match(files.devicePanel, /physical_ios_live_actions_enabled/)
  assert.match(files.devicePanel, /physical_ios_appium_xcuitest/)
  assert.match(files.devicePanel, /Default:/)
  assert.match(files.devicePanel, /Sender device topology/)
  assert.match(files.devicePanel, /deviceTopology/)
  assert.match(files.devicePanel, /review edit approve monitor/)
  assert.match(files.devicePanel, /Secondary iPhone/)
  assert.doesNotMatch(files.devicePanel, /\/api\/device-control\/action/)
  assert.doesNotMatch(files.devicePanel, /confirm_live_action/)
})


test('device-control job status route scopes lookup by authenticated user', () => {
  assert.match(files.jobStatus, /agent_jobs:getById/)
  assert.match(files.jobStatus, /agent_jobs:listForUser/)
  assert.match(files.jobStatus, /user_id: user\.id/)
  assert.match(files.jobStatus, /Job not found/)
  assert.match(files.devicePanel, /\/api\/device-control\/jobs\/\$\{jobId\}/)
  assert.match(files.devicePanel, /Job status:/)
})
