-- AI-8763: voice training UI — chat.db-derived style digest column.
--
-- The agent computes a JSON digest locally (clapcheeks.voice.clone)
-- and PATCHes it into clapcheeks_voice_profiles. The web /studio/voice
-- page reads it back to render stats + "tone calibration" UI. Adding
-- as JSONB lets us evolve the digest schema without further migrations.
--
-- The pre-existing columns (style_summary, sample_phrases, tone,
-- profile_data, messages_analyzed) stay populated by the older
-- /api/conversation/voice-profile route — both paths coexist.

ALTER TABLE public.clapcheeks_voice_profiles
  ADD COLUMN IF NOT EXISTS digest JSONB DEFAULT '{}'::JSONB;

-- Curated subset of sample messages the operator picked as "most like me"
-- in the /studio/voice tone-calibration UI. Stored separately so the raw
-- digest column can be regenerated by `clapcheeks voice scan` without
-- losing the operator's manual boosts.
ALTER TABLE public.clapcheeks_voice_profiles
  ADD COLUMN IF NOT EXISTS boosted_samples JSONB DEFAULT '[]'::JSONB;

-- Track when the chat.db scan last ran (separate from updated_at, which
-- bumps on any column write).
ALTER TABLE public.clapcheeks_voice_profiles
  ADD COLUMN IF NOT EXISTS last_scan_at TIMESTAMPTZ;

COMMENT ON COLUMN public.clapcheeks_voice_profiles.digest IS
  'AI-8763: chat.db-derived style digest (avg length, emoji ratio, openers, '
  'common phrases, slang dictionary, time-of-day clusters, sample_messages). '
  'Computed by clapcheeks.voice.clone.compute_style_digest. Used as few-shot '
  'in agent/clapcheeks/imessage/ai_reply.ReplyGenerator.';

COMMENT ON COLUMN public.clapcheeks_voice_profiles.boosted_samples IS
  'AI-8763: operator-selected sample messages that feel "most like me". '
  'Placed first in the few-shot example list during reply generation.';

COMMENT ON COLUMN public.clapcheeks_voice_profiles.last_scan_at IS
  'AI-8763: timestamp of the most recent `clapcheeks voice scan` that '
  'wrote to this row.';
