/* eslint-disable no-console */
// One-shot migration: Supabase Postgres → Convex.
// Linear: AI-9196 — Phase 3 messaging engine cutover.
//
// Run flow:
//   1. Ensure CONVEX_URL + CONVEX_DEPLOY_KEY env vars are set (post `npx convex dev` first run)
//   2. Ensure SUPABASE_URL + SUPABASE_SERVICE_KEY are set (clapcheeks project, not Dashboard Daddy)
//   3. Dry run first: `npx tsx scripts/migrate-postgres-to-convex.ts --dry-run`
//   4. Real run: `npx tsx scripts/migrate-postgres-to-convex.ts`
//
// What it copies:
//   - public.clapcheeks_scheduled_messages → conversations + scheduled_messages
//   - public.clapcheeks_agent_jobs         → agent_jobs
//   - Drip state on clapcheeks_matches     → drip_states (optional, see DRIP_BACKFILL flag)
//
// What stays on Postgres (NOT migrated, intentional):
//   - users, profiles, subscriptions, billing, photos, analytics
//   - clapcheeks_matches (partial — drip columns become Convex; rest stays for the auth/RLS layer)
//
// Deletion of Postgres source rows is NOT part of this script. Soak Convex
// for ≥ 1 week before dropping the source tables in a separate migration.

import { createClient } from '@supabase/supabase-js';
import { ConvexHttpClient } from 'convex/browser';

// Lazy import; api.* is generated by `npx convex dev` and won't exist on a
// fresh checkout, but we don't need it at import time — call by string name.
type ConvexFn = string;

const DRY_RUN = process.argv.includes('--dry-run');
const DRIP_BACKFILL = process.argv.includes('--drip');
const BATCH_SIZE = 200;

const SUPABASE_URL = process.env.SUPABASE_URL;
const SUPABASE_SERVICE_KEY =
  process.env.SUPABASE_SERVICE_ROLE_KEY ||
  process.env.SUPABASE_SERVICE_KEY;
const CONVEX_URL = process.env.CONVEX_URL || process.env.NEXT_PUBLIC_CONVEX_URL;

if (!SUPABASE_URL || !SUPABASE_SERVICE_KEY) {
  console.error('SUPABASE_URL and SUPABASE_SERVICE_KEY must be set');
  process.exit(1);
}
if (!CONVEX_URL) {
  console.error('CONVEX_URL or NEXT_PUBLIC_CONVEX_URL must be set');
  process.exit(1);
}

const supabase = createClient(SUPABASE_URL, SUPABASE_SERVICE_KEY, {
  auth: { persistSession: false },
});

const convex = new ConvexHttpClient(CONVEX_URL);

// Status mapping: PG → Convex
function mapScheduledStatus(pg: string): 'pending' | 'sent' | 'cancelled' | 'failed' {
  switch (pg) {
    case 'pending':
    case 'approved':
      return 'pending'; // approved means user OK'd it; will be picked up by Convex cron and sent
    case 'rejected':
      return 'cancelled';
    case 'sent':
      return 'sent';
    case 'failed':
      return 'failed';
    default:
      return 'cancelled';
  }
}

function mapJobStatus(
  pg: string,
): 'queued' | 'running' | 'completed' | 'failed' | 'cancelled' {
  switch (pg) {
    case 'pending':
      return 'queued';
    case 'claimed':
    case 'in_progress':
      return 'running';
    case 'completed':
      return 'completed';
    case 'failed':
      return 'failed';
    case 'stale_no_extension':
      return 'failed';
    default:
      return 'cancelled';
  }
}

async function migrateScheduledMessages() {
  console.log('\n=== clapcheeks_scheduled_messages → conversations + scheduled_messages ===');

  let from = 0;
  let migrated = 0;
  const conversationCache = new Map<string, string>(); // user_id+platform+match_name -> convex conv id

  while (true) {
    const { data, error } = await supabase
      .from('clapcheeks_scheduled_messages')
      .select('*')
      .order('created_at', { ascending: true })
      .range(from, from + BATCH_SIZE - 1);

    if (error) throw error;
    if (!data || data.length === 0) break;

    for (const row of data) {
      const cacheKey = `${row.user_id}|${row.platform}|${row.match_name}`;
      let convId = conversationCache.get(cacheKey);

      if (!convId) {
        const externalId = row.phone || row.match_name; // fallback when phone is null

        if (DRY_RUN) {
          convId = `dry-${cacheKey}`;
        } else {
          convId = (await convex.mutation('conversations:upsert' as ConvexFn, {
            user_id: row.user_id,
            platform: row.platform === 'iMessage' ? 'imessage' : row.platform.toLowerCase(),
            external_match_id: externalId,
            match_name: row.match_name,
          })) as string;
        }
        conversationCache.set(cacheKey, convId);
      }

      const scheduledFor = new Date(row.scheduled_at).getTime();
      const payload = {
        conversation_id: convId,
        user_id: row.user_id,
        body: row.message_text,
        scheduled_for: scheduledFor,
        schedule_reason: row.sequence_type ?? undefined,
      };

      if (DRY_RUN) {
        console.log('  [dry] would insert scheduled_message:', payload);
      } else {
        // Use a custom-args internalMutation if you prefer to also set status from PG;
        // create() forces 'pending' so we manually patch via the create+overwrite path.
        const id = (await convex.mutation(
          'scheduled_messages:create' as ConvexFn,
          payload,
        )) as string;
        const newStatus = mapScheduledStatus(row.status);
        if (newStatus !== 'pending') {
          // No public mutation overrides status; for now leave a comment for follow-up
          // or extend convex/scheduled_messages.ts with an internal `_setStatus` mutation
          // (omitted for safety — the data integrity matters more than perfect status).
          console.warn(
            `  [warn] sched ${id} kept as 'pending' though PG had '${row.status}'`,
          );
        }
      }
      migrated++;
    }
    from += BATCH_SIZE;
  }

  console.log(`migrated ${migrated} scheduled message rows; ${conversationCache.size} unique conversations`);
}

async function migrateAgentJobs() {
  console.log('\n=== clapcheeks_agent_jobs → agent_jobs ===');
  let from = 0;
  let migrated = 0;
  while (true) {
    const { data, error } = await supabase
      .from('clapcheeks_agent_jobs')
      .select('*')
      .order('created_at', { ascending: true })
      .range(from, from + BATCH_SIZE - 1);
    if (error) throw error;
    if (!data || data.length === 0) break;

    for (const row of data) {
      const payload = {
        user_id: row.user_id,
        job_type: row.job_type,
        payload: row.job_params,
        priority: 0,
        max_attempts: 3,
      };
      if (DRY_RUN) {
        console.log('  [dry] would enqueue:', { ...payload, status: mapJobStatus(row.status) });
      } else {
        await convex.mutation('agent_jobs:enqueue' as ConvexFn, payload);
        // Same caveat as scheduled_messages — full status replication would
        // need an _import mutation that bypasses the public enqueue contract.
      }
      migrated++;
    }
    from += BATCH_SIZE;
  }
  console.log(`migrated ${migrated} agent_jobs rows`);
}

async function migrateDripStates() {
  if (!DRIP_BACKFILL) {
    console.log('\n=== drip_states === (skipped — pass --drip to backfill)');
    return;
  }
  console.log('\n=== clapcheeks_matches drip columns → drip_states ===');
  // Drip lives as columns on clapcheeks_matches: read out the relevant subset.
  const { data, error } = await supabase
    .from('clapcheeks_matches')
    .select('id, user_id, drip_state, next_action_at, cool_down_until, consecutive_no_reply, match_name, platform, external_match_id')
    .not('drip_state', 'is', null)
    .limit(5000);
  if (error) throw error;
  console.log(`found ${data?.length ?? 0} matches with drip state`);
  if (DRY_RUN) {
    console.log(`  [dry] would create ${data?.length ?? 0} drip_states rows`);
    return;
  }
  // Real run: upsert conversation first, then drip state — left as TODO since
  // the Postgres column names need verification against the actual schema.
  console.warn('drip backfill not yet implemented — verify column names first');
}

async function main() {
  console.log(DRY_RUN ? 'DRY RUN — no writes will be made' : 'LIVE RUN');
  console.log('Source:', SUPABASE_URL);
  console.log('Target:', CONVEX_URL);
  await migrateScheduledMessages();
  await migrateAgentJobs();
  await migrateDripStates();
  console.log('\nDONE.');
}

main().catch((err) => {
  console.error('FATAL:', err);
  process.exit(1);
});
